// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wavespan/v1/backup.proto

package wavespanv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/yannick/wavespan/proto/wavespan/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BackupServiceName is the fully-qualified name of the BackupService service.
	BackupServiceName = "wavespan.v1.BackupService"
	// BackupNodeServiceName is the fully-qualified name of the BackupNodeService service.
	BackupNodeServiceName = "wavespan.v1.BackupNodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BackupServiceBeginBackupProcedure is the fully-qualified name of the BackupService's BeginBackup
	// RPC.
	BackupServiceBeginBackupProcedure = "/wavespan.v1.BackupService/BeginBackup"
	// BackupServiceBackupStatusProcedure is the fully-qualified name of the BackupService's
	// BackupStatus RPC.
	BackupServiceBackupStatusProcedure = "/wavespan.v1.BackupService/BackupStatus"
	// BackupServiceListBackupsProcedure is the fully-qualified name of the BackupService's ListBackups
	// RPC.
	BackupServiceListBackupsProcedure = "/wavespan.v1.BackupService/ListBackups"
	// BackupServiceDeleteBackupProcedure is the fully-qualified name of the BackupService's
	// DeleteBackup RPC.
	BackupServiceDeleteBackupProcedure = "/wavespan.v1.BackupService/DeleteBackup"
	// BackupServiceListDestinationsProcedure is the fully-qualified name of the BackupService's
	// ListDestinations RPC.
	BackupServiceListDestinationsProcedure = "/wavespan.v1.BackupService/ListDestinations"
	// BackupNodeServicePrepareBackupProcedure is the fully-qualified name of the BackupNodeService's
	// PrepareBackup RPC.
	BackupNodeServicePrepareBackupProcedure = "/wavespan.v1.BackupNodeService/PrepareBackup"
	// BackupNodeServiceExportBackupProcedure is the fully-qualified name of the BackupNodeService's
	// ExportBackup RPC.
	BackupNodeServiceExportBackupProcedure = "/wavespan.v1.BackupNodeService/ExportBackup"
)

// BackupServiceClient is a client for the wavespan.v1.BackupService service.
type BackupServiceClient interface {
	// BeginBackup records a durable BackupIntent, picks a cluster HLC frontier, and drives the
	// phased backup (assign/prepare/export/commit), returning the allocated backup id.
	BeginBackup(context.Context, *connect.Request[v1.BeginBackupRequest]) (*connect.Response[v1.BeginBackupResult], error)
	// BackupStatus reports a backup's current state (status, phase, per-node progress, gaps).
	BackupStatus(context.Context, *connect.Request[v1.BackupStatusRequest]) (*connect.Response[v1.BackupState], error)
	// ListBackups lists known backups from the meta-shard catalog.
	ListBackups(context.Context, *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResult], error)
	// DeleteBackup removes a backup's catalog intent and its objects, chain-aware (force cascades).
	DeleteBackup(context.Context, *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResult], error)
	// ListDestinations reports the node's configured backup destinations (default + named) for the admin
	// UI. It returns only non-secret descriptor fields — never any credential.
	ListDestinations(context.Context, *connect.Request[v1.ListDestinationsRequest]) (*connect.Response[v1.ListDestinationsResult], error)
}

// NewBackupServiceClient constructs a client for the wavespan.v1.BackupService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBackupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BackupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	backupServiceMethods := v1.File_wavespan_v1_backup_proto.Services().ByName("BackupService").Methods()
	return &backupServiceClient{
		beginBackup: connect.NewClient[v1.BeginBackupRequest, v1.BeginBackupResult](
			httpClient,
			baseURL+BackupServiceBeginBackupProcedure,
			connect.WithSchema(backupServiceMethods.ByName("BeginBackup")),
			connect.WithClientOptions(opts...),
		),
		backupStatus: connect.NewClient[v1.BackupStatusRequest, v1.BackupState](
			httpClient,
			baseURL+BackupServiceBackupStatusProcedure,
			connect.WithSchema(backupServiceMethods.ByName("BackupStatus")),
			connect.WithClientOptions(opts...),
		),
		listBackups: connect.NewClient[v1.ListBackupsRequest, v1.ListBackupsResult](
			httpClient,
			baseURL+BackupServiceListBackupsProcedure,
			connect.WithSchema(backupServiceMethods.ByName("ListBackups")),
			connect.WithClientOptions(opts...),
		),
		deleteBackup: connect.NewClient[v1.DeleteBackupRequest, v1.DeleteBackupResult](
			httpClient,
			baseURL+BackupServiceDeleteBackupProcedure,
			connect.WithSchema(backupServiceMethods.ByName("DeleteBackup")),
			connect.WithClientOptions(opts...),
		),
		listDestinations: connect.NewClient[v1.ListDestinationsRequest, v1.ListDestinationsResult](
			httpClient,
			baseURL+BackupServiceListDestinationsProcedure,
			connect.WithSchema(backupServiceMethods.ByName("ListDestinations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// backupServiceClient implements BackupServiceClient.
type backupServiceClient struct {
	beginBackup      *connect.Client[v1.BeginBackupRequest, v1.BeginBackupResult]
	backupStatus     *connect.Client[v1.BackupStatusRequest, v1.BackupState]
	listBackups      *connect.Client[v1.ListBackupsRequest, v1.ListBackupsResult]
	deleteBackup     *connect.Client[v1.DeleteBackupRequest, v1.DeleteBackupResult]
	listDestinations *connect.Client[v1.ListDestinationsRequest, v1.ListDestinationsResult]
}

// BeginBackup calls wavespan.v1.BackupService.BeginBackup.
func (c *backupServiceClient) BeginBackup(ctx context.Context, req *connect.Request[v1.BeginBackupRequest]) (*connect.Response[v1.BeginBackupResult], error) {
	return c.beginBackup.CallUnary(ctx, req)
}

// BackupStatus calls wavespan.v1.BackupService.BackupStatus.
func (c *backupServiceClient) BackupStatus(ctx context.Context, req *connect.Request[v1.BackupStatusRequest]) (*connect.Response[v1.BackupState], error) {
	return c.backupStatus.CallUnary(ctx, req)
}

// ListBackups calls wavespan.v1.BackupService.ListBackups.
func (c *backupServiceClient) ListBackups(ctx context.Context, req *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResult], error) {
	return c.listBackups.CallUnary(ctx, req)
}

// DeleteBackup calls wavespan.v1.BackupService.DeleteBackup.
func (c *backupServiceClient) DeleteBackup(ctx context.Context, req *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResult], error) {
	return c.deleteBackup.CallUnary(ctx, req)
}

// ListDestinations calls wavespan.v1.BackupService.ListDestinations.
func (c *backupServiceClient) ListDestinations(ctx context.Context, req *connect.Request[v1.ListDestinationsRequest]) (*connect.Response[v1.ListDestinationsResult], error) {
	return c.listDestinations.CallUnary(ctx, req)
}

// BackupServiceHandler is an implementation of the wavespan.v1.BackupService service.
type BackupServiceHandler interface {
	// BeginBackup records a durable BackupIntent, picks a cluster HLC frontier, and drives the
	// phased backup (assign/prepare/export/commit), returning the allocated backup id.
	BeginBackup(context.Context, *connect.Request[v1.BeginBackupRequest]) (*connect.Response[v1.BeginBackupResult], error)
	// BackupStatus reports a backup's current state (status, phase, per-node progress, gaps).
	BackupStatus(context.Context, *connect.Request[v1.BackupStatusRequest]) (*connect.Response[v1.BackupState], error)
	// ListBackups lists known backups from the meta-shard catalog.
	ListBackups(context.Context, *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResult], error)
	// DeleteBackup removes a backup's catalog intent and its objects, chain-aware (force cascades).
	DeleteBackup(context.Context, *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResult], error)
	// ListDestinations reports the node's configured backup destinations (default + named) for the admin
	// UI. It returns only non-secret descriptor fields — never any credential.
	ListDestinations(context.Context, *connect.Request[v1.ListDestinationsRequest]) (*connect.Response[v1.ListDestinationsResult], error)
}

// NewBackupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBackupServiceHandler(svc BackupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	backupServiceMethods := v1.File_wavespan_v1_backup_proto.Services().ByName("BackupService").Methods()
	backupServiceBeginBackupHandler := connect.NewUnaryHandler(
		BackupServiceBeginBackupProcedure,
		svc.BeginBackup,
		connect.WithSchema(backupServiceMethods.ByName("BeginBackup")),
		connect.WithHandlerOptions(opts...),
	)
	backupServiceBackupStatusHandler := connect.NewUnaryHandler(
		BackupServiceBackupStatusProcedure,
		svc.BackupStatus,
		connect.WithSchema(backupServiceMethods.ByName("BackupStatus")),
		connect.WithHandlerOptions(opts...),
	)
	backupServiceListBackupsHandler := connect.NewUnaryHandler(
		BackupServiceListBackupsProcedure,
		svc.ListBackups,
		connect.WithSchema(backupServiceMethods.ByName("ListBackups")),
		connect.WithHandlerOptions(opts...),
	)
	backupServiceDeleteBackupHandler := connect.NewUnaryHandler(
		BackupServiceDeleteBackupProcedure,
		svc.DeleteBackup,
		connect.WithSchema(backupServiceMethods.ByName("DeleteBackup")),
		connect.WithHandlerOptions(opts...),
	)
	backupServiceListDestinationsHandler := connect.NewUnaryHandler(
		BackupServiceListDestinationsProcedure,
		svc.ListDestinations,
		connect.WithSchema(backupServiceMethods.ByName("ListDestinations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wavespan.v1.BackupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BackupServiceBeginBackupProcedure:
			backupServiceBeginBackupHandler.ServeHTTP(w, r)
		case BackupServiceBackupStatusProcedure:
			backupServiceBackupStatusHandler.ServeHTTP(w, r)
		case BackupServiceListBackupsProcedure:
			backupServiceListBackupsHandler.ServeHTTP(w, r)
		case BackupServiceDeleteBackupProcedure:
			backupServiceDeleteBackupHandler.ServeHTTP(w, r)
		case BackupServiceListDestinationsProcedure:
			backupServiceListDestinationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBackupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBackupServiceHandler struct{}

func (UnimplementedBackupServiceHandler) BeginBackup(context.Context, *connect.Request[v1.BeginBackupRequest]) (*connect.Response[v1.BeginBackupResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BackupService.BeginBackup is not implemented"))
}

func (UnimplementedBackupServiceHandler) BackupStatus(context.Context, *connect.Request[v1.BackupStatusRequest]) (*connect.Response[v1.BackupState], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BackupService.BackupStatus is not implemented"))
}

func (UnimplementedBackupServiceHandler) ListBackups(context.Context, *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BackupService.ListBackups is not implemented"))
}

func (UnimplementedBackupServiceHandler) DeleteBackup(context.Context, *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BackupService.DeleteBackup is not implemented"))
}

func (UnimplementedBackupServiceHandler) ListDestinations(context.Context, *connect.Request[v1.ListDestinationsRequest]) (*connect.Response[v1.ListDestinationsResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BackupService.ListDestinations is not implemented"))
}

// BackupNodeServiceClient is a client for the wavespan.v1.BackupNodeService service.
type BackupNodeServiceClient interface {
	// PrepareBackup (node-internal) seals the node's view at the frontier and reports held ranges.
	PrepareBackup(context.Context, *connect.Request[v1.PrepareBackupRequest]) (*connect.Response[v1.PrepareBackupResult], error)
	// ExportBackup (node-internal) exports this node's assignment to the request-supplied object store.
	ExportBackup(context.Context, *connect.Request[v1.ExportBackupRequest]) (*connect.Response[v1.ExportBackupResult], error)
}

// NewBackupNodeServiceClient constructs a client for the wavespan.v1.BackupNodeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBackupNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BackupNodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	backupNodeServiceMethods := v1.File_wavespan_v1_backup_proto.Services().ByName("BackupNodeService").Methods()
	return &backupNodeServiceClient{
		prepareBackup: connect.NewClient[v1.PrepareBackupRequest, v1.PrepareBackupResult](
			httpClient,
			baseURL+BackupNodeServicePrepareBackupProcedure,
			connect.WithSchema(backupNodeServiceMethods.ByName("PrepareBackup")),
			connect.WithClientOptions(opts...),
		),
		exportBackup: connect.NewClient[v1.ExportBackupRequest, v1.ExportBackupResult](
			httpClient,
			baseURL+BackupNodeServiceExportBackupProcedure,
			connect.WithSchema(backupNodeServiceMethods.ByName("ExportBackup")),
			connect.WithClientOptions(opts...),
		),
	}
}

// backupNodeServiceClient implements BackupNodeServiceClient.
type backupNodeServiceClient struct {
	prepareBackup *connect.Client[v1.PrepareBackupRequest, v1.PrepareBackupResult]
	exportBackup  *connect.Client[v1.ExportBackupRequest, v1.ExportBackupResult]
}

// PrepareBackup calls wavespan.v1.BackupNodeService.PrepareBackup.
func (c *backupNodeServiceClient) PrepareBackup(ctx context.Context, req *connect.Request[v1.PrepareBackupRequest]) (*connect.Response[v1.PrepareBackupResult], error) {
	return c.prepareBackup.CallUnary(ctx, req)
}

// ExportBackup calls wavespan.v1.BackupNodeService.ExportBackup.
func (c *backupNodeServiceClient) ExportBackup(ctx context.Context, req *connect.Request[v1.ExportBackupRequest]) (*connect.Response[v1.ExportBackupResult], error) {
	return c.exportBackup.CallUnary(ctx, req)
}

// BackupNodeServiceHandler is an implementation of the wavespan.v1.BackupNodeService service.
type BackupNodeServiceHandler interface {
	// PrepareBackup (node-internal) seals the node's view at the frontier and reports held ranges.
	PrepareBackup(context.Context, *connect.Request[v1.PrepareBackupRequest]) (*connect.Response[v1.PrepareBackupResult], error)
	// ExportBackup (node-internal) exports this node's assignment to the request-supplied object store.
	ExportBackup(context.Context, *connect.Request[v1.ExportBackupRequest]) (*connect.Response[v1.ExportBackupResult], error)
}

// NewBackupNodeServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBackupNodeServiceHandler(svc BackupNodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	backupNodeServiceMethods := v1.File_wavespan_v1_backup_proto.Services().ByName("BackupNodeService").Methods()
	backupNodeServicePrepareBackupHandler := connect.NewUnaryHandler(
		BackupNodeServicePrepareBackupProcedure,
		svc.PrepareBackup,
		connect.WithSchema(backupNodeServiceMethods.ByName("PrepareBackup")),
		connect.WithHandlerOptions(opts...),
	)
	backupNodeServiceExportBackupHandler := connect.NewUnaryHandler(
		BackupNodeServiceExportBackupProcedure,
		svc.ExportBackup,
		connect.WithSchema(backupNodeServiceMethods.ByName("ExportBackup")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wavespan.v1.BackupNodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BackupNodeServicePrepareBackupProcedure:
			backupNodeServicePrepareBackupHandler.ServeHTTP(w, r)
		case BackupNodeServiceExportBackupProcedure:
			backupNodeServiceExportBackupHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBackupNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBackupNodeServiceHandler struct{}

func (UnimplementedBackupNodeServiceHandler) PrepareBackup(context.Context, *connect.Request[v1.PrepareBackupRequest]) (*connect.Response[v1.PrepareBackupResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BackupNodeService.PrepareBackup is not implemented"))
}

func (UnimplementedBackupNodeServiceHandler) ExportBackup(context.Context, *connect.Request[v1.ExportBackupRequest]) (*connect.Response[v1.ExportBackupResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BackupNodeService.ExportBackup is not implemented"))
}
