// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wavespan/v1/budget.proto

package wavespanv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/yannick/wavespan/proto/wavespan/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BudgetServiceName is the fully-qualified name of the BudgetService service.
	BudgetServiceName = "wavespan.v1.BudgetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BudgetServiceBudgetDefineProcedure is the fully-qualified name of the BudgetService's
	// BudgetDefine RPC.
	BudgetServiceBudgetDefineProcedure = "/wavespan.v1.BudgetService/BudgetDefine"
	// BudgetServiceBudgetGrantProcedure is the fully-qualified name of the BudgetService's BudgetGrant
	// RPC.
	BudgetServiceBudgetGrantProcedure = "/wavespan.v1.BudgetService/BudgetGrant"
	// BudgetServiceBudgetReportProcedure is the fully-qualified name of the BudgetService's
	// BudgetReport RPC.
	BudgetServiceBudgetReportProcedure = "/wavespan.v1.BudgetService/BudgetReport"
	// BudgetServiceBudgetReturnProcedure is the fully-qualified name of the BudgetService's
	// BudgetReturn RPC.
	BudgetServiceBudgetReturnProcedure = "/wavespan.v1.BudgetService/BudgetReturn"
	// BudgetServiceBudgetStatProcedure is the fully-qualified name of the BudgetService's BudgetStat
	// RPC.
	BudgetServiceBudgetStatProcedure = "/wavespan.v1.BudgetService/BudgetStat"
)

// BudgetServiceClient is a client for the wavespan.v1.BudgetService service.
type BudgetServiceClient interface {
	// BudgetDefine creates a STRICT pool with the given cap. A non-STRICT mode or invalid cap fails with
	// InvalidArgument; defining an existing pool fails with FailedPrecondition.
	BudgetDefine(context.Context, *connect.Request[v1.BudgetDefineRequest]) (*connect.Response[v1.BudgetStatResult], error)
	// BudgetGrant atomically leases up to amount_units; lease_id makes the grant idempotent for the
	// lease's lifetime. A pool with nothing left returns no_capacity (a normal result, not an error).
	BudgetGrant(context.Context, *connect.Request[v1.BudgetGrantRequest]) (*connect.Response[v1.BudgetGrantResult], error)
	// BudgetReport folds a cumulative-per-lease spent total (idempotent max fold).
	BudgetReport(context.Context, *connect.Request[v1.BudgetReportRequest]) (*connect.Response[v1.BudgetStatResult], error)
	// BudgetReturn releases a lease's unspent remainder and deletes the lease row.
	BudgetReturn(context.Context, *connect.Request[v1.BudgetReturnRequest]) (*connect.Response[v1.BudgetStatResult], error)
	// BudgetStat reads the pool accounting (bounded-stale unless linearizable).
	BudgetStat(context.Context, *connect.Request[v1.BudgetStatRequest]) (*connect.Response[v1.BudgetStatResult], error)
}

// NewBudgetServiceClient constructs a client for the wavespan.v1.BudgetService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBudgetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BudgetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	budgetServiceMethods := v1.File_wavespan_v1_budget_proto.Services().ByName("BudgetService").Methods()
	return &budgetServiceClient{
		budgetDefine: connect.NewClient[v1.BudgetDefineRequest, v1.BudgetStatResult](
			httpClient,
			baseURL+BudgetServiceBudgetDefineProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("BudgetDefine")),
			connect.WithClientOptions(opts...),
		),
		budgetGrant: connect.NewClient[v1.BudgetGrantRequest, v1.BudgetGrantResult](
			httpClient,
			baseURL+BudgetServiceBudgetGrantProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("BudgetGrant")),
			connect.WithClientOptions(opts...),
		),
		budgetReport: connect.NewClient[v1.BudgetReportRequest, v1.BudgetStatResult](
			httpClient,
			baseURL+BudgetServiceBudgetReportProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("BudgetReport")),
			connect.WithClientOptions(opts...),
		),
		budgetReturn: connect.NewClient[v1.BudgetReturnRequest, v1.BudgetStatResult](
			httpClient,
			baseURL+BudgetServiceBudgetReturnProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("BudgetReturn")),
			connect.WithClientOptions(opts...),
		),
		budgetStat: connect.NewClient[v1.BudgetStatRequest, v1.BudgetStatResult](
			httpClient,
			baseURL+BudgetServiceBudgetStatProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("BudgetStat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// budgetServiceClient implements BudgetServiceClient.
type budgetServiceClient struct {
	budgetDefine *connect.Client[v1.BudgetDefineRequest, v1.BudgetStatResult]
	budgetGrant  *connect.Client[v1.BudgetGrantRequest, v1.BudgetGrantResult]
	budgetReport *connect.Client[v1.BudgetReportRequest, v1.BudgetStatResult]
	budgetReturn *connect.Client[v1.BudgetReturnRequest, v1.BudgetStatResult]
	budgetStat   *connect.Client[v1.BudgetStatRequest, v1.BudgetStatResult]
}

// BudgetDefine calls wavespan.v1.BudgetService.BudgetDefine.
func (c *budgetServiceClient) BudgetDefine(ctx context.Context, req *connect.Request[v1.BudgetDefineRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return c.budgetDefine.CallUnary(ctx, req)
}

// BudgetGrant calls wavespan.v1.BudgetService.BudgetGrant.
func (c *budgetServiceClient) BudgetGrant(ctx context.Context, req *connect.Request[v1.BudgetGrantRequest]) (*connect.Response[v1.BudgetGrantResult], error) {
	return c.budgetGrant.CallUnary(ctx, req)
}

// BudgetReport calls wavespan.v1.BudgetService.BudgetReport.
func (c *budgetServiceClient) BudgetReport(ctx context.Context, req *connect.Request[v1.BudgetReportRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return c.budgetReport.CallUnary(ctx, req)
}

// BudgetReturn calls wavespan.v1.BudgetService.BudgetReturn.
func (c *budgetServiceClient) BudgetReturn(ctx context.Context, req *connect.Request[v1.BudgetReturnRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return c.budgetReturn.CallUnary(ctx, req)
}

// BudgetStat calls wavespan.v1.BudgetService.BudgetStat.
func (c *budgetServiceClient) BudgetStat(ctx context.Context, req *connect.Request[v1.BudgetStatRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return c.budgetStat.CallUnary(ctx, req)
}

// BudgetServiceHandler is an implementation of the wavespan.v1.BudgetService service.
type BudgetServiceHandler interface {
	// BudgetDefine creates a STRICT pool with the given cap. A non-STRICT mode or invalid cap fails with
	// InvalidArgument; defining an existing pool fails with FailedPrecondition.
	BudgetDefine(context.Context, *connect.Request[v1.BudgetDefineRequest]) (*connect.Response[v1.BudgetStatResult], error)
	// BudgetGrant atomically leases up to amount_units; lease_id makes the grant idempotent for the
	// lease's lifetime. A pool with nothing left returns no_capacity (a normal result, not an error).
	BudgetGrant(context.Context, *connect.Request[v1.BudgetGrantRequest]) (*connect.Response[v1.BudgetGrantResult], error)
	// BudgetReport folds a cumulative-per-lease spent total (idempotent max fold).
	BudgetReport(context.Context, *connect.Request[v1.BudgetReportRequest]) (*connect.Response[v1.BudgetStatResult], error)
	// BudgetReturn releases a lease's unspent remainder and deletes the lease row.
	BudgetReturn(context.Context, *connect.Request[v1.BudgetReturnRequest]) (*connect.Response[v1.BudgetStatResult], error)
	// BudgetStat reads the pool accounting (bounded-stale unless linearizable).
	BudgetStat(context.Context, *connect.Request[v1.BudgetStatRequest]) (*connect.Response[v1.BudgetStatResult], error)
}

// NewBudgetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBudgetServiceHandler(svc BudgetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	budgetServiceMethods := v1.File_wavespan_v1_budget_proto.Services().ByName("BudgetService").Methods()
	budgetServiceBudgetDefineHandler := connect.NewUnaryHandler(
		BudgetServiceBudgetDefineProcedure,
		svc.BudgetDefine,
		connect.WithSchema(budgetServiceMethods.ByName("BudgetDefine")),
		connect.WithHandlerOptions(opts...),
	)
	budgetServiceBudgetGrantHandler := connect.NewUnaryHandler(
		BudgetServiceBudgetGrantProcedure,
		svc.BudgetGrant,
		connect.WithSchema(budgetServiceMethods.ByName("BudgetGrant")),
		connect.WithHandlerOptions(opts...),
	)
	budgetServiceBudgetReportHandler := connect.NewUnaryHandler(
		BudgetServiceBudgetReportProcedure,
		svc.BudgetReport,
		connect.WithSchema(budgetServiceMethods.ByName("BudgetReport")),
		connect.WithHandlerOptions(opts...),
	)
	budgetServiceBudgetReturnHandler := connect.NewUnaryHandler(
		BudgetServiceBudgetReturnProcedure,
		svc.BudgetReturn,
		connect.WithSchema(budgetServiceMethods.ByName("BudgetReturn")),
		connect.WithHandlerOptions(opts...),
	)
	budgetServiceBudgetStatHandler := connect.NewUnaryHandler(
		BudgetServiceBudgetStatProcedure,
		svc.BudgetStat,
		connect.WithSchema(budgetServiceMethods.ByName("BudgetStat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wavespan.v1.BudgetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BudgetServiceBudgetDefineProcedure:
			budgetServiceBudgetDefineHandler.ServeHTTP(w, r)
		case BudgetServiceBudgetGrantProcedure:
			budgetServiceBudgetGrantHandler.ServeHTTP(w, r)
		case BudgetServiceBudgetReportProcedure:
			budgetServiceBudgetReportHandler.ServeHTTP(w, r)
		case BudgetServiceBudgetReturnProcedure:
			budgetServiceBudgetReturnHandler.ServeHTTP(w, r)
		case BudgetServiceBudgetStatProcedure:
			budgetServiceBudgetStatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBudgetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBudgetServiceHandler struct{}

func (UnimplementedBudgetServiceHandler) BudgetDefine(context.Context, *connect.Request[v1.BudgetDefineRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BudgetService.BudgetDefine is not implemented"))
}

func (UnimplementedBudgetServiceHandler) BudgetGrant(context.Context, *connect.Request[v1.BudgetGrantRequest]) (*connect.Response[v1.BudgetGrantResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BudgetService.BudgetGrant is not implemented"))
}

func (UnimplementedBudgetServiceHandler) BudgetReport(context.Context, *connect.Request[v1.BudgetReportRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BudgetService.BudgetReport is not implemented"))
}

func (UnimplementedBudgetServiceHandler) BudgetReturn(context.Context, *connect.Request[v1.BudgetReturnRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BudgetService.BudgetReturn is not implemented"))
}

func (UnimplementedBudgetServiceHandler) BudgetStat(context.Context, *connect.Request[v1.BudgetStatRequest]) (*connect.Response[v1.BudgetStatResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.BudgetService.BudgetStat is not implemented"))
}
