// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wavespan/v1/observability.proto

package wavespanv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cwire/wavespan/proto/wavespan/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ObservabilityServiceName is the fully-qualified name of the ObservabilityService service.
	ObservabilityServiceName = "wavespan.v1.ObservabilityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ObservabilityServiceStreamGossipProcedure is the fully-qualified name of the
	// ObservabilityService's StreamGossip RPC.
	ObservabilityServiceStreamGossipProcedure = "/wavespan.v1.ObservabilityService/StreamGossip"
	// ObservabilityServiceInspectLocalProcedure is the fully-qualified name of the
	// ObservabilityService's InspectLocal RPC.
	ObservabilityServiceInspectLocalProcedure = "/wavespan.v1.ObservabilityService/InspectLocal"
	// ObservabilityServiceInspectGlobalProcedure is the fully-qualified name of the
	// ObservabilityService's InspectGlobal RPC.
	ObservabilityServiceInspectGlobalProcedure = "/wavespan.v1.ObservabilityService/InspectGlobal"
	// ObservabilityServiceGetClusterViewProcedure is the fully-qualified name of the
	// ObservabilityService's GetClusterView RPC.
	ObservabilityServiceGetClusterViewProcedure = "/wavespan.v1.ObservabilityService/GetClusterView"
	// ObservabilityServiceGraphExploreProcedure is the fully-qualified name of the
	// ObservabilityService's GraphExplore RPC.
	ObservabilityServiceGraphExploreProcedure = "/wavespan.v1.ObservabilityService/GraphExplore"
)

// ObservabilityServiceClient is a client for the wavespan.v1.ObservabilityService service.
type ObservabilityServiceClient interface {
	StreamGossip(context.Context, *connect.Request[v1.StreamGossipRequest]) (*connect.ServerStreamForClient[v1.GossipEvent], error)
	InspectLocal(context.Context, *connect.Request[v1.InspectLocalRequest]) (*connect.ServerStreamForClient[v1.InspectRow], error)
	InspectGlobal(context.Context, *connect.Request[v1.InspectGlobalRequest]) (*connect.ServerStreamForClient[v1.InspectRow], error)
	GetClusterView(context.Context, *connect.Request[v1.GetClusterViewRequest]) (*connect.Response[v1.GetClusterViewResponse], error)
	GraphExplore(context.Context, *connect.Request[v1.GraphExploreRequest]) (*connect.Response[v1.GraphExploreResponse], error)
}

// NewObservabilityServiceClient constructs a client for the wavespan.v1.ObservabilityService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObservabilityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ObservabilityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	observabilityServiceMethods := v1.File_wavespan_v1_observability_proto.Services().ByName("ObservabilityService").Methods()
	return &observabilityServiceClient{
		streamGossip: connect.NewClient[v1.StreamGossipRequest, v1.GossipEvent](
			httpClient,
			baseURL+ObservabilityServiceStreamGossipProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("StreamGossip")),
			connect.WithClientOptions(opts...),
		),
		inspectLocal: connect.NewClient[v1.InspectLocalRequest, v1.InspectRow](
			httpClient,
			baseURL+ObservabilityServiceInspectLocalProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("InspectLocal")),
			connect.WithClientOptions(opts...),
		),
		inspectGlobal: connect.NewClient[v1.InspectGlobalRequest, v1.InspectRow](
			httpClient,
			baseURL+ObservabilityServiceInspectGlobalProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("InspectGlobal")),
			connect.WithClientOptions(opts...),
		),
		getClusterView: connect.NewClient[v1.GetClusterViewRequest, v1.GetClusterViewResponse](
			httpClient,
			baseURL+ObservabilityServiceGetClusterViewProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("GetClusterView")),
			connect.WithClientOptions(opts...),
		),
		graphExplore: connect.NewClient[v1.GraphExploreRequest, v1.GraphExploreResponse](
			httpClient,
			baseURL+ObservabilityServiceGraphExploreProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("GraphExplore")),
			connect.WithClientOptions(opts...),
		),
	}
}

// observabilityServiceClient implements ObservabilityServiceClient.
type observabilityServiceClient struct {
	streamGossip   *connect.Client[v1.StreamGossipRequest, v1.GossipEvent]
	inspectLocal   *connect.Client[v1.InspectLocalRequest, v1.InspectRow]
	inspectGlobal  *connect.Client[v1.InspectGlobalRequest, v1.InspectRow]
	getClusterView *connect.Client[v1.GetClusterViewRequest, v1.GetClusterViewResponse]
	graphExplore   *connect.Client[v1.GraphExploreRequest, v1.GraphExploreResponse]
}

// StreamGossip calls wavespan.v1.ObservabilityService.StreamGossip.
func (c *observabilityServiceClient) StreamGossip(ctx context.Context, req *connect.Request[v1.StreamGossipRequest]) (*connect.ServerStreamForClient[v1.GossipEvent], error) {
	return c.streamGossip.CallServerStream(ctx, req)
}

// InspectLocal calls wavespan.v1.ObservabilityService.InspectLocal.
func (c *observabilityServiceClient) InspectLocal(ctx context.Context, req *connect.Request[v1.InspectLocalRequest]) (*connect.ServerStreamForClient[v1.InspectRow], error) {
	return c.inspectLocal.CallServerStream(ctx, req)
}

// InspectGlobal calls wavespan.v1.ObservabilityService.InspectGlobal.
func (c *observabilityServiceClient) InspectGlobal(ctx context.Context, req *connect.Request[v1.InspectGlobalRequest]) (*connect.ServerStreamForClient[v1.InspectRow], error) {
	return c.inspectGlobal.CallServerStream(ctx, req)
}

// GetClusterView calls wavespan.v1.ObservabilityService.GetClusterView.
func (c *observabilityServiceClient) GetClusterView(ctx context.Context, req *connect.Request[v1.GetClusterViewRequest]) (*connect.Response[v1.GetClusterViewResponse], error) {
	return c.getClusterView.CallUnary(ctx, req)
}

// GraphExplore calls wavespan.v1.ObservabilityService.GraphExplore.
func (c *observabilityServiceClient) GraphExplore(ctx context.Context, req *connect.Request[v1.GraphExploreRequest]) (*connect.Response[v1.GraphExploreResponse], error) {
	return c.graphExplore.CallUnary(ctx, req)
}

// ObservabilityServiceHandler is an implementation of the wavespan.v1.ObservabilityService service.
type ObservabilityServiceHandler interface {
	StreamGossip(context.Context, *connect.Request[v1.StreamGossipRequest], *connect.ServerStream[v1.GossipEvent]) error
	InspectLocal(context.Context, *connect.Request[v1.InspectLocalRequest], *connect.ServerStream[v1.InspectRow]) error
	InspectGlobal(context.Context, *connect.Request[v1.InspectGlobalRequest], *connect.ServerStream[v1.InspectRow]) error
	GetClusterView(context.Context, *connect.Request[v1.GetClusterViewRequest]) (*connect.Response[v1.GetClusterViewResponse], error)
	GraphExplore(context.Context, *connect.Request[v1.GraphExploreRequest]) (*connect.Response[v1.GraphExploreResponse], error)
}

// NewObservabilityServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObservabilityServiceHandler(svc ObservabilityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	observabilityServiceMethods := v1.File_wavespan_v1_observability_proto.Services().ByName("ObservabilityService").Methods()
	observabilityServiceStreamGossipHandler := connect.NewServerStreamHandler(
		ObservabilityServiceStreamGossipProcedure,
		svc.StreamGossip,
		connect.WithSchema(observabilityServiceMethods.ByName("StreamGossip")),
		connect.WithHandlerOptions(opts...),
	)
	observabilityServiceInspectLocalHandler := connect.NewServerStreamHandler(
		ObservabilityServiceInspectLocalProcedure,
		svc.InspectLocal,
		connect.WithSchema(observabilityServiceMethods.ByName("InspectLocal")),
		connect.WithHandlerOptions(opts...),
	)
	observabilityServiceInspectGlobalHandler := connect.NewServerStreamHandler(
		ObservabilityServiceInspectGlobalProcedure,
		svc.InspectGlobal,
		connect.WithSchema(observabilityServiceMethods.ByName("InspectGlobal")),
		connect.WithHandlerOptions(opts...),
	)
	observabilityServiceGetClusterViewHandler := connect.NewUnaryHandler(
		ObservabilityServiceGetClusterViewProcedure,
		svc.GetClusterView,
		connect.WithSchema(observabilityServiceMethods.ByName("GetClusterView")),
		connect.WithHandlerOptions(opts...),
	)
	observabilityServiceGraphExploreHandler := connect.NewUnaryHandler(
		ObservabilityServiceGraphExploreProcedure,
		svc.GraphExplore,
		connect.WithSchema(observabilityServiceMethods.ByName("GraphExplore")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wavespan.v1.ObservabilityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ObservabilityServiceStreamGossipProcedure:
			observabilityServiceStreamGossipHandler.ServeHTTP(w, r)
		case ObservabilityServiceInspectLocalProcedure:
			observabilityServiceInspectLocalHandler.ServeHTTP(w, r)
		case ObservabilityServiceInspectGlobalProcedure:
			observabilityServiceInspectGlobalHandler.ServeHTTP(w, r)
		case ObservabilityServiceGetClusterViewProcedure:
			observabilityServiceGetClusterViewHandler.ServeHTTP(w, r)
		case ObservabilityServiceGraphExploreProcedure:
			observabilityServiceGraphExploreHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedObservabilityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObservabilityServiceHandler struct{}

func (UnimplementedObservabilityServiceHandler) StreamGossip(context.Context, *connect.Request[v1.StreamGossipRequest], *connect.ServerStream[v1.GossipEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.ObservabilityService.StreamGossip is not implemented"))
}

func (UnimplementedObservabilityServiceHandler) InspectLocal(context.Context, *connect.Request[v1.InspectLocalRequest], *connect.ServerStream[v1.InspectRow]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.ObservabilityService.InspectLocal is not implemented"))
}

func (UnimplementedObservabilityServiceHandler) InspectGlobal(context.Context, *connect.Request[v1.InspectGlobalRequest], *connect.ServerStream[v1.InspectRow]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.ObservabilityService.InspectGlobal is not implemented"))
}

func (UnimplementedObservabilityServiceHandler) GetClusterView(context.Context, *connect.Request[v1.GetClusterViewRequest]) (*connect.Response[v1.GetClusterViewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.ObservabilityService.GetClusterView is not implemented"))
}

func (UnimplementedObservabilityServiceHandler) GraphExplore(context.Context, *connect.Request[v1.GraphExploreRequest]) (*connect.Response[v1.GraphExploreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.ObservabilityService.GraphExplore is not implemented"))
}
