// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wavespan/v1/replication.proto

package wavespanv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cwire/wavespan/proto/wavespan/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReplicationServiceName is the fully-qualified name of the ReplicationService service.
	ReplicationServiceName = "wavespan.v1.ReplicationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReplicationServiceStoreReplicaProcedure is the fully-qualified name of the ReplicationService's
	// StoreReplica RPC.
	ReplicationServiceStoreReplicaProcedure = "/wavespan.v1.ReplicationService/StoreReplica"
)

// ReplicationServiceClient is a client for the wavespan.v1.ReplicationService service.
type ReplicationServiceClient interface {
	StoreReplica(context.Context, *connect.Request[v1.StoreReplicaRequest]) (*connect.Response[v1.StoreReplicaResponse], error)
}

// NewReplicationServiceClient constructs a client for the wavespan.v1.ReplicationService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReplicationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReplicationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	replicationServiceMethods := v1.File_wavespan_v1_replication_proto.Services().ByName("ReplicationService").Methods()
	return &replicationServiceClient{
		storeReplica: connect.NewClient[v1.StoreReplicaRequest, v1.StoreReplicaResponse](
			httpClient,
			baseURL+ReplicationServiceStoreReplicaProcedure,
			connect.WithSchema(replicationServiceMethods.ByName("StoreReplica")),
			connect.WithClientOptions(opts...),
		),
	}
}

// replicationServiceClient implements ReplicationServiceClient.
type replicationServiceClient struct {
	storeReplica *connect.Client[v1.StoreReplicaRequest, v1.StoreReplicaResponse]
}

// StoreReplica calls wavespan.v1.ReplicationService.StoreReplica.
func (c *replicationServiceClient) StoreReplica(ctx context.Context, req *connect.Request[v1.StoreReplicaRequest]) (*connect.Response[v1.StoreReplicaResponse], error) {
	return c.storeReplica.CallUnary(ctx, req)
}

// ReplicationServiceHandler is an implementation of the wavespan.v1.ReplicationService service.
type ReplicationServiceHandler interface {
	StoreReplica(context.Context, *connect.Request[v1.StoreReplicaRequest]) (*connect.Response[v1.StoreReplicaResponse], error)
}

// NewReplicationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReplicationServiceHandler(svc ReplicationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	replicationServiceMethods := v1.File_wavespan_v1_replication_proto.Services().ByName("ReplicationService").Methods()
	replicationServiceStoreReplicaHandler := connect.NewUnaryHandler(
		ReplicationServiceStoreReplicaProcedure,
		svc.StoreReplica,
		connect.WithSchema(replicationServiceMethods.ByName("StoreReplica")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wavespan.v1.ReplicationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReplicationServiceStoreReplicaProcedure:
			replicationServiceStoreReplicaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReplicationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReplicationServiceHandler struct{}

func (UnimplementedReplicationServiceHandler) StoreReplica(context.Context, *connect.Request[v1.StoreReplicaRequest]) (*connect.Response[v1.StoreReplicaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.ReplicationService.StoreReplica is not implemented"))
}
