// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wavespan/v1/vector.proto

package wavespanv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cwire/wavespan/proto/wavespan/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VectorServiceName is the fully-qualified name of the VectorService service.
	VectorServiceName = "wavespan.v1.VectorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VectorServicePutProcedure is the fully-qualified name of the VectorService's Put RPC.
	VectorServicePutProcedure = "/wavespan.v1.VectorService/Put"
)

// VectorServiceClient is a client for the wavespan.v1.VectorService service.
type VectorServiceClient interface {
	Put(context.Context, *connect.Request[v1.PutVectorRequest]) (*connect.Response[v1.PutVectorResponse], error)
}

// NewVectorServiceClient constructs a client for the wavespan.v1.VectorService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVectorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VectorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	vectorServiceMethods := v1.File_wavespan_v1_vector_proto.Services().ByName("VectorService").Methods()
	return &vectorServiceClient{
		put: connect.NewClient[v1.PutVectorRequest, v1.PutVectorResponse](
			httpClient,
			baseURL+VectorServicePutProcedure,
			connect.WithSchema(vectorServiceMethods.ByName("Put")),
			connect.WithClientOptions(opts...),
		),
	}
}

// vectorServiceClient implements VectorServiceClient.
type vectorServiceClient struct {
	put *connect.Client[v1.PutVectorRequest, v1.PutVectorResponse]
}

// Put calls wavespan.v1.VectorService.Put.
func (c *vectorServiceClient) Put(ctx context.Context, req *connect.Request[v1.PutVectorRequest]) (*connect.Response[v1.PutVectorResponse], error) {
	return c.put.CallUnary(ctx, req)
}

// VectorServiceHandler is an implementation of the wavespan.v1.VectorService service.
type VectorServiceHandler interface {
	Put(context.Context, *connect.Request[v1.PutVectorRequest]) (*connect.Response[v1.PutVectorResponse], error)
}

// NewVectorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVectorServiceHandler(svc VectorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	vectorServiceMethods := v1.File_wavespan_v1_vector_proto.Services().ByName("VectorService").Methods()
	vectorServicePutHandler := connect.NewUnaryHandler(
		VectorServicePutProcedure,
		svc.Put,
		connect.WithSchema(vectorServiceMethods.ByName("Put")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wavespan.v1.VectorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VectorServicePutProcedure:
			vectorServicePutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVectorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVectorServiceHandler struct{}

func (UnimplementedVectorServiceHandler) Put(context.Context, *connect.Request[v1.PutVectorRequest]) (*connect.Response[v1.PutVectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wavespan.v1.VectorService.Put is not implemented"))
}
