// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: wavespan/v1/backup.proto

package wavespanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackupService_BeginBackup_FullMethodName   = "/wavespan.v1.BackupService/BeginBackup"
	BackupService_BackupStatus_FullMethodName  = "/wavespan.v1.BackupService/BackupStatus"
	BackupService_ListBackups_FullMethodName   = "/wavespan.v1.BackupService/ListBackups"
	BackupService_DeleteBackup_FullMethodName  = "/wavespan.v1.BackupService/DeleteBackup"
	BackupService_PrepareBackup_FullMethodName = "/wavespan.v1.BackupService/PrepareBackup"
	BackupService_ExportBackup_FullMethodName  = "/wavespan.v1.BackupService/ExportBackup"
)

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackupService coordinates and executes consistent cluster backups to an object store
// (design/backup phase 3). Admin-facing RPCs (BeginBackup/BackupStatus/ListBackups/DeleteBackup)
// are exposed on the Connect admin port; the node-internal PrepareBackup/ExportBackup RPCs are
// fanned out by the coordinator to each node over the gRPC data port. Every result carries
// ResponseMeta. This phase (3a) covers full backup only.
type BackupServiceClient interface {
	// BeginBackup records a durable BackupIntent, picks a cluster HLC frontier, and drives the
	// phased backup (assign/prepare/export/commit), returning the allocated backup id.
	BeginBackup(ctx context.Context, in *BeginBackupRequest, opts ...grpc.CallOption) (*BeginBackupResult, error)
	// BackupStatus reports a backup's current state (status, phase, per-node progress, gaps).
	BackupStatus(ctx context.Context, in *BackupStatusRequest, opts ...grpc.CallOption) (*BackupState, error)
	// ListBackups lists known backups from the meta-shard catalog.
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResult, error)
	// DeleteBackup removes a backup's catalog intent (object GC is Phase 3d).
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResult, error)
	// PrepareBackup (node-internal) seals the node's view at the frontier and reports held ranges.
	PrepareBackup(ctx context.Context, in *PrepareBackupRequest, opts ...grpc.CallOption) (*PrepareBackupResult, error)
	// ExportBackup (node-internal) exports this node's assignment to the object store.
	ExportBackup(ctx context.Context, in *ExportBackupRequest, opts ...grpc.CallOption) (*ExportBackupResult, error)
}

type backupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupServiceClient(cc grpc.ClientConnInterface) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) BeginBackup(ctx context.Context, in *BeginBackupRequest, opts ...grpc.CallOption) (*BeginBackupResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginBackupResult)
	err := c.cc.Invoke(ctx, BackupService_BeginBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) BackupStatus(ctx context.Context, in *BackupStatusRequest, opts ...grpc.CallOption) (*BackupState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupState)
	err := c.cc.Invoke(ctx, BackupService_BackupStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResult)
	err := c.cc.Invoke(ctx, BackupService_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBackupResult)
	err := c.cc.Invoke(ctx, BackupService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) PrepareBackup(ctx context.Context, in *PrepareBackupRequest, opts ...grpc.CallOption) (*PrepareBackupResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareBackupResult)
	err := c.cc.Invoke(ctx, BackupService_PrepareBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ExportBackup(ctx context.Context, in *ExportBackupRequest, opts ...grpc.CallOption) (*ExportBackupResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportBackupResult)
	err := c.cc.Invoke(ctx, BackupService_ExportBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
// All implementations must embed UnimplementedBackupServiceServer
// for forward compatibility.
//
// BackupService coordinates and executes consistent cluster backups to an object store
// (design/backup phase 3). Admin-facing RPCs (BeginBackup/BackupStatus/ListBackups/DeleteBackup)
// are exposed on the Connect admin port; the node-internal PrepareBackup/ExportBackup RPCs are
// fanned out by the coordinator to each node over the gRPC data port. Every result carries
// ResponseMeta. This phase (3a) covers full backup only.
type BackupServiceServer interface {
	// BeginBackup records a durable BackupIntent, picks a cluster HLC frontier, and drives the
	// phased backup (assign/prepare/export/commit), returning the allocated backup id.
	BeginBackup(context.Context, *BeginBackupRequest) (*BeginBackupResult, error)
	// BackupStatus reports a backup's current state (status, phase, per-node progress, gaps).
	BackupStatus(context.Context, *BackupStatusRequest) (*BackupState, error)
	// ListBackups lists known backups from the meta-shard catalog.
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResult, error)
	// DeleteBackup removes a backup's catalog intent (object GC is Phase 3d).
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResult, error)
	// PrepareBackup (node-internal) seals the node's view at the frontier and reports held ranges.
	PrepareBackup(context.Context, *PrepareBackupRequest) (*PrepareBackupResult, error)
	// ExportBackup (node-internal) exports this node's assignment to the object store.
	ExportBackup(context.Context, *ExportBackupRequest) (*ExportBackupResult, error)
	mustEmbedUnimplementedBackupServiceServer()
}

// UnimplementedBackupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServiceServer struct{}

func (UnimplementedBackupServiceServer) BeginBackup(context.Context, *BeginBackupRequest) (*BeginBackupResult, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginBackup not implemented")
}
func (UnimplementedBackupServiceServer) BackupStatus(context.Context, *BackupStatusRequest) (*BackupState, error) {
	return nil, status.Error(codes.Unimplemented, "method BackupStatus not implemented")
}
func (UnimplementedBackupServiceServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedBackupServiceServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedBackupServiceServer) PrepareBackup(context.Context, *PrepareBackupRequest) (*PrepareBackupResult, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareBackup not implemented")
}
func (UnimplementedBackupServiceServer) ExportBackup(context.Context, *ExportBackupRequest) (*ExportBackupResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportBackup not implemented")
}
func (UnimplementedBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {}
func (UnimplementedBackupServiceServer) testEmbeddedByValue()                       {}

// UnsafeBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServiceServer will
// result in compilation errors.
type UnsafeBackupServiceServer interface {
	mustEmbedUnimplementedBackupServiceServer()
}

func RegisterBackupServiceServer(s grpc.ServiceRegistrar, srv BackupServiceServer) {
	// If the following call panics, it indicates UnimplementedBackupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupService_ServiceDesc, srv)
}

func _BackupService_BeginBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).BeginBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_BeginBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).BeginBackup(ctx, req.(*BeginBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_BackupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).BackupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_BackupStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).BackupStatus(ctx, req.(*BackupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_PrepareBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).PrepareBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_PrepareBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).PrepareBackup(ctx, req.(*PrepareBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ExportBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ExportBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ExportBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ExportBackup(ctx, req.(*ExportBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupService_ServiceDesc is the grpc.ServiceDesc for BackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wavespan.v1.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginBackup",
			Handler:    _BackupService_BeginBackup_Handler,
		},
		{
			MethodName: "BackupStatus",
			Handler:    _BackupService_BackupStatus_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _BackupService_ListBackups_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _BackupService_DeleteBackup_Handler,
		},
		{
			MethodName: "PrepareBackup",
			Handler:    _BackupService_PrepareBackup_Handler,
		},
		{
			MethodName: "ExportBackup",
			Handler:    _BackupService_ExportBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wavespan/v1/backup.proto",
}
