// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wavespan/v1/collections.proto

package wavespanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposeForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection    []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Command       []byte                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // the engine-encoded write command (opaque on the wire)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeForwardRequest) Reset() {
	*x = ProposeForwardRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeForwardRequest) ProtoMessage() {}

func (x *ProposeForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeForwardRequest.ProtoReflect.Descriptor instead.
func (*ProposeForwardRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{0}
}

func (x *ProposeForwardRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ProposeForwardRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *ProposeForwardRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type AdmitLearnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId     uint64                 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // the joining node's Raft transport address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitLearnerRequest) Reset() {
	*x = AdmitLearnerRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitLearnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitLearnerRequest) ProtoMessage() {}

func (x *AdmitLearnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitLearnerRequest.ProtoReflect.Descriptor instead.
func (*AdmitLearnerRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{1}
}

func (x *AdmitLearnerRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AdmitLearnerRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *AdmitLearnerRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type AdmitLearnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitLearnerResponse) Reset() {
	*x = AdmitLearnerResponse{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitLearnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitLearnerResponse) ProtoMessage() {}

func (x *AdmitLearnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitLearnerResponse.ProtoReflect.Descriptor instead.
func (*AdmitLearnerResponse) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{2}
}

func (x *AdmitLearnerResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// FieldValue is a hash field/value pair.
type FieldValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         []byte                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{3}
}

func (x *FieldValue) GetField() []byte {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *FieldValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// ScoredMember is a sorted-set member and its score.
type ScoredMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        []byte                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredMember) Reset() {
	*x = ScoredMember{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredMember) ProtoMessage() {}

func (x *ScoredMember) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredMember.ProtoReflect.Descriptor instead.
func (*ScoredMember) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{4}
}

func (x *ScoredMember) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *ScoredMember) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SAddRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Namespace  string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Members    [][]byte               `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	// ttl_ms, when set, makes each added member expire after the given duration (log-driven, design/30 §10).
	TtlMs *int64 `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3,oneof" json:"ttl_ms,omitempty"`
	// idempotency_key dedupes a retried write so it applies exactly once (design/30 §13.12).
	IdempotencyKey *string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SAddRequest) Reset() {
	*x = SAddRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddRequest) ProtoMessage() {}

func (x *SAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddRequest.ProtoReflect.Descriptor instead.
func (*SAddRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{5}
}

func (x *SAddRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SAddRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *SAddRequest) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *SAddRequest) GetTtlMs() int64 {
	if x != nil && x.TtlMs != nil {
		return *x.TtlMs
	}
	return 0
}

func (x *SAddRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

// KeysRequest removes members/fields (SRem, HDel, ZRem).
type KeysRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection     []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Keys           [][]byte               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	IdempotencyKey *string                `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeysRequest) Reset() {
	*x = KeysRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRequest) ProtoMessage() {}

func (x *KeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRequest.ProtoReflect.Descriptor instead.
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{6}
}

func (x *KeysRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KeysRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *KeysRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeysRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

// MemberRequest reads a single member/field (SIsMember, HGet, ZScore).
type MemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection    []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Member        []byte                 `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	Linearizable  bool                   `protobuf:"varint,4,opt,name=linearizable,proto3" json:"linearizable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRequest) Reset() {
	*x = MemberRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRequest) ProtoMessage() {}

func (x *MemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRequest.ProtoReflect.Descriptor instead.
func (*MemberRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{7}
}

func (x *MemberRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MemberRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *MemberRequest) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *MemberRequest) GetLinearizable() bool {
	if x != nil {
		return x.Linearizable
	}
	return false
}

// CardRequest reads a cardinality (SCard, HLen, ZCard).
type CardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection    []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Linearizable  bool                   `protobuf:"varint,3,opt,name=linearizable,proto3" json:"linearizable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{8}
}

func (x *CardRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CardRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *CardRequest) GetLinearizable() bool {
	if x != nil {
		return x.Linearizable
	}
	return false
}

// RangeRequest enumerates a collection (SMembers, HGetAll, ZRange).
type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection    []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = all
	Linearizable  bool                   `protobuf:"varint,4,opt,name=linearizable,proto3" json:"linearizable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{9}
}

func (x *RangeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RangeRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *RangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RangeRequest) GetLinearizable() bool {
	if x != nil {
		return x.Linearizable
	}
	return false
}

type HSetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection     []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Fields         []*FieldValue          `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	IdempotencyKey *string                `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HSetRequest) Reset() {
	*x = HSetRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetRequest) ProtoMessage() {}

func (x *HSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetRequest.ProtoReflect.Descriptor instead.
func (*HSetRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{10}
}

func (x *HSetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HSetRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *HSetRequest) GetFields() []*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *HSetRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type ZAddRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Collection     []byte                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Members        []*ScoredMember        `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	IdempotencyKey *string                `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ZAddRequest) Reset() {
	*x = ZAddRequest{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZAddRequest) ProtoMessage() {}

func (x *ZAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZAddRequest.ProtoReflect.Descriptor instead.
func (*ZAddRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{11}
}

func (x *ZAddRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ZAddRequest) GetCollection() []byte {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *ZAddRequest) GetMembers() []*ScoredMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ZAddRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type CountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResult) Reset() {
	*x = CountResult{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResult) ProtoMessage() {}

func (x *CountResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResult.ProtoReflect.Descriptor instead.
func (*CountResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{12}
}

func (x *CountResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CountResult) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BoolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResult) Reset() {
	*x = BoolResult{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResult) ProtoMessage() {}

func (x *BoolResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResult.ProtoReflect.Descriptor instead.
func (*BoolResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{13}
}

func (x *BoolResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BoolResult) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ValueResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueResult) Reset() {
	*x = ValueResult{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueResult) ProtoMessage() {}

func (x *ValueResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueResult.ProtoReflect.Descriptor instead.
func (*ValueResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{14}
}

func (x *ValueResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ValueResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ValueResult) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ScoreResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResult) Reset() {
	*x = ScoreResult{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResult) ProtoMessage() {}

func (x *ScoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResult.ProtoReflect.Descriptor instead.
func (*ScoreResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{15}
}

func (x *ScoreResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ScoreResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ScoreResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type MembersResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Members       [][]byte               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersResult) Reset() {
	*x = MembersResult{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersResult) ProtoMessage() {}

func (x *MembersResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersResult.ProtoReflect.Descriptor instead.
func (*MembersResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{16}
}

func (x *MembersResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MembersResult) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

type FieldsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Fields        []*FieldValue          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsResult) Reset() {
	*x = FieldsResult{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsResult) ProtoMessage() {}

func (x *FieldsResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsResult.ProtoReflect.Descriptor instead.
func (*FieldsResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{17}
}

func (x *FieldsResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FieldsResult) GetFields() []*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ScoredMembersResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Members       []*ScoredMember        `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredMembersResult) Reset() {
	*x = ScoredMembersResult{}
	mi := &file_wavespan_v1_collections_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredMembersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredMembersResult) ProtoMessage() {}

func (x *ScoredMembersResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_collections_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredMembersResult.ProtoReflect.Descriptor instead.
func (*ScoredMembersResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_collections_proto_rawDescGZIP(), []int{18}
}

func (x *ScoredMembersResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ScoredMembersResult) GetMembers() []*ScoredMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_wavespan_v1_collections_proto protoreflect.FileDescriptor

const file_wavespan_v1_collections_proto_rawDesc = "" +
	"\n" +
	"\x1dwavespan/v1/collections.proto\x12\vwavespan.v1\x1a\x18wavespan/v1/common.proto\"o\n" +
	"\x15ProposeForwardRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x12\x18\n" +
	"\acommand\x18\x03 \x01(\fR\acommand\"g\n" +
	"\x13AdmitLearnerRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"E\n" +
	"\x14AdmitLearnerResponse\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\"8\n" +
	"\n" +
	"FieldValue\x12\x14\n" +
	"\x05field\x18\x01 \x01(\fR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"<\n" +
	"\fScoredMember\x12\x16\n" +
	"\x06member\x18\x01 \x01(\fR\x06member\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"\xce\x01\n" +
	"\vSAddRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x12\x18\n" +
	"\amembers\x18\x03 \x03(\fR\amembers\x12\x1a\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03H\x00R\x05ttlMs\x88\x01\x01\x12,\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tH\x01R\x0eidempotencyKey\x88\x01\x01B\t\n" +
	"\a_ttl_msB\x12\n" +
	"\x10_idempotency_key\"\xa1\x01\n" +
	"\vKeysRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\fR\x04keys\x12,\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01B\x12\n" +
	"\x10_idempotency_key\"\x89\x01\n" +
	"\rMemberRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x12\x16\n" +
	"\x06member\x18\x03 \x01(\fR\x06member\x12\"\n" +
	"\flinearizable\x18\x04 \x01(\bR\flinearizable\"o\n" +
	"\vCardRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x12\"\n" +
	"\flinearizable\x18\x03 \x01(\bR\flinearizable\"\x86\x01\n" +
	"\fRangeRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\"\n" +
	"\flinearizable\x18\x04 \x01(\bR\flinearizable\"\xbe\x01\n" +
	"\vHSetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x12/\n" +
	"\x06fields\x18\x03 \x03(\v2\x17.wavespan.v1.FieldValueR\x06fields\x12,\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01B\x12\n" +
	"\x10_idempotency_key\"\xc2\x01\n" +
	"\vZAddRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\fR\n" +
	"collection\x123\n" +
	"\amembers\x18\x03 \x03(\v2\x19.wavespan.v1.ScoredMemberR\amembers\x12,\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01B\x12\n" +
	"\x10_idempotency_key\"R\n" +
	"\vCountResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"Q\n" +
	"\n" +
	"BoolResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"h\n" +
	"\vValueResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"h\n" +
	"\vScoreResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"X\n" +
	"\rMembersResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12\x18\n" +
	"\amembers\x18\x02 \x03(\fR\amembers\"n\n" +
	"\fFieldsResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12/\n" +
	"\x06fields\x18\x02 \x03(\v2\x17.wavespan.v1.FieldValueR\x06fields\"y\n" +
	"\x13ScoredMembersResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x123\n" +
	"\amembers\x18\x02 \x03(\v2\x19.wavespan.v1.ScoredMemberR\amembers2\xe1\b\n" +
	"\x11CollectionService\x12:\n" +
	"\x04SAdd\x12\x18.wavespan.v1.SAddRequest\x1a\x18.wavespan.v1.CountResult\x12:\n" +
	"\x04SRem\x12\x18.wavespan.v1.KeysRequest\x1a\x18.wavespan.v1.CountResult\x12@\n" +
	"\tSIsMember\x12\x1a.wavespan.v1.MemberRequest\x1a\x17.wavespan.v1.BoolResult\x12;\n" +
	"\x05SCard\x12\x18.wavespan.v1.CardRequest\x1a\x18.wavespan.v1.CountResult\x12A\n" +
	"\bSMembers\x12\x19.wavespan.v1.RangeRequest\x1a\x1a.wavespan.v1.MembersResult\x12:\n" +
	"\x04HSet\x12\x18.wavespan.v1.HSetRequest\x1a\x18.wavespan.v1.CountResult\x12:\n" +
	"\x04HDel\x12\x18.wavespan.v1.KeysRequest\x1a\x18.wavespan.v1.CountResult\x12<\n" +
	"\x04HGet\x12\x1a.wavespan.v1.MemberRequest\x1a\x18.wavespan.v1.ValueResult\x12:\n" +
	"\x04HLen\x12\x18.wavespan.v1.CardRequest\x1a\x18.wavespan.v1.CountResult\x12?\n" +
	"\aHGetAll\x12\x19.wavespan.v1.RangeRequest\x1a\x19.wavespan.v1.FieldsResult\x12:\n" +
	"\x04ZAdd\x12\x18.wavespan.v1.ZAddRequest\x1a\x18.wavespan.v1.CountResult\x12:\n" +
	"\x04ZRem\x12\x18.wavespan.v1.KeysRequest\x1a\x18.wavespan.v1.CountResult\x12>\n" +
	"\x06ZScore\x12\x1a.wavespan.v1.MemberRequest\x1a\x18.wavespan.v1.ScoreResult\x12;\n" +
	"\x05ZCard\x12\x18.wavespan.v1.CardRequest\x1a\x18.wavespan.v1.CountResult\x12E\n" +
	"\x06ZRange\x12\x19.wavespan.v1.RangeRequest\x1a .wavespan.v1.ScoredMembersResult\x12S\n" +
	"\fAdmitLearner\x12 .wavespan.v1.AdmitLearnerRequest\x1a!.wavespan.v1.AdmitLearnerResponse\x12N\n" +
	"\x0eProposeForward\x12\".wavespan.v1.ProposeForwardRequest\x1a\x18.wavespan.v1.CountResultB\xaa\x01\n" +
	"\x0fcom.wavespan.v1B\x10CollectionsProtoP\x01Z8github.com/yannick/wavespan/proto/wavespan/v1;wavespanv1\xa2\x02\x03WXX\xaa\x02\vWavespan.V1\xca\x02\vWavespan\\V1\xe2\x02\x17Wavespan\\V1\\GPBMetadata\xea\x02\fWavespan::V1b\x06proto3"

var (
	file_wavespan_v1_collections_proto_rawDescOnce sync.Once
	file_wavespan_v1_collections_proto_rawDescData []byte
)

func file_wavespan_v1_collections_proto_rawDescGZIP() []byte {
	file_wavespan_v1_collections_proto_rawDescOnce.Do(func() {
		file_wavespan_v1_collections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wavespan_v1_collections_proto_rawDesc), len(file_wavespan_v1_collections_proto_rawDesc)))
	})
	return file_wavespan_v1_collections_proto_rawDescData
}

var file_wavespan_v1_collections_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_wavespan_v1_collections_proto_goTypes = []any{
	(*ProposeForwardRequest)(nil), // 0: wavespan.v1.ProposeForwardRequest
	(*AdmitLearnerRequest)(nil),   // 1: wavespan.v1.AdmitLearnerRequest
	(*AdmitLearnerResponse)(nil),  // 2: wavespan.v1.AdmitLearnerResponse
	(*FieldValue)(nil),            // 3: wavespan.v1.FieldValue
	(*ScoredMember)(nil),          // 4: wavespan.v1.ScoredMember
	(*SAddRequest)(nil),           // 5: wavespan.v1.SAddRequest
	(*KeysRequest)(nil),           // 6: wavespan.v1.KeysRequest
	(*MemberRequest)(nil),         // 7: wavespan.v1.MemberRequest
	(*CardRequest)(nil),           // 8: wavespan.v1.CardRequest
	(*RangeRequest)(nil),          // 9: wavespan.v1.RangeRequest
	(*HSetRequest)(nil),           // 10: wavespan.v1.HSetRequest
	(*ZAddRequest)(nil),           // 11: wavespan.v1.ZAddRequest
	(*CountResult)(nil),           // 12: wavespan.v1.CountResult
	(*BoolResult)(nil),            // 13: wavespan.v1.BoolResult
	(*ValueResult)(nil),           // 14: wavespan.v1.ValueResult
	(*ScoreResult)(nil),           // 15: wavespan.v1.ScoreResult
	(*MembersResult)(nil),         // 16: wavespan.v1.MembersResult
	(*FieldsResult)(nil),          // 17: wavespan.v1.FieldsResult
	(*ScoredMembersResult)(nil),   // 18: wavespan.v1.ScoredMembersResult
	(*ResponseMeta)(nil),          // 19: wavespan.v1.ResponseMeta
}
var file_wavespan_v1_collections_proto_depIdxs = []int32{
	19, // 0: wavespan.v1.AdmitLearnerResponse.meta:type_name -> wavespan.v1.ResponseMeta
	3,  // 1: wavespan.v1.HSetRequest.fields:type_name -> wavespan.v1.FieldValue
	4,  // 2: wavespan.v1.ZAddRequest.members:type_name -> wavespan.v1.ScoredMember
	19, // 3: wavespan.v1.CountResult.meta:type_name -> wavespan.v1.ResponseMeta
	19, // 4: wavespan.v1.BoolResult.meta:type_name -> wavespan.v1.ResponseMeta
	19, // 5: wavespan.v1.ValueResult.meta:type_name -> wavespan.v1.ResponseMeta
	19, // 6: wavespan.v1.ScoreResult.meta:type_name -> wavespan.v1.ResponseMeta
	19, // 7: wavespan.v1.MembersResult.meta:type_name -> wavespan.v1.ResponseMeta
	19, // 8: wavespan.v1.FieldsResult.meta:type_name -> wavespan.v1.ResponseMeta
	3,  // 9: wavespan.v1.FieldsResult.fields:type_name -> wavespan.v1.FieldValue
	19, // 10: wavespan.v1.ScoredMembersResult.meta:type_name -> wavespan.v1.ResponseMeta
	4,  // 11: wavespan.v1.ScoredMembersResult.members:type_name -> wavespan.v1.ScoredMember
	5,  // 12: wavespan.v1.CollectionService.SAdd:input_type -> wavespan.v1.SAddRequest
	6,  // 13: wavespan.v1.CollectionService.SRem:input_type -> wavespan.v1.KeysRequest
	7,  // 14: wavespan.v1.CollectionService.SIsMember:input_type -> wavespan.v1.MemberRequest
	8,  // 15: wavespan.v1.CollectionService.SCard:input_type -> wavespan.v1.CardRequest
	9,  // 16: wavespan.v1.CollectionService.SMembers:input_type -> wavespan.v1.RangeRequest
	10, // 17: wavespan.v1.CollectionService.HSet:input_type -> wavespan.v1.HSetRequest
	6,  // 18: wavespan.v1.CollectionService.HDel:input_type -> wavespan.v1.KeysRequest
	7,  // 19: wavespan.v1.CollectionService.HGet:input_type -> wavespan.v1.MemberRequest
	8,  // 20: wavespan.v1.CollectionService.HLen:input_type -> wavespan.v1.CardRequest
	9,  // 21: wavespan.v1.CollectionService.HGetAll:input_type -> wavespan.v1.RangeRequest
	11, // 22: wavespan.v1.CollectionService.ZAdd:input_type -> wavespan.v1.ZAddRequest
	6,  // 23: wavespan.v1.CollectionService.ZRem:input_type -> wavespan.v1.KeysRequest
	7,  // 24: wavespan.v1.CollectionService.ZScore:input_type -> wavespan.v1.MemberRequest
	8,  // 25: wavespan.v1.CollectionService.ZCard:input_type -> wavespan.v1.CardRequest
	9,  // 26: wavespan.v1.CollectionService.ZRange:input_type -> wavespan.v1.RangeRequest
	1,  // 27: wavespan.v1.CollectionService.AdmitLearner:input_type -> wavespan.v1.AdmitLearnerRequest
	0,  // 28: wavespan.v1.CollectionService.ProposeForward:input_type -> wavespan.v1.ProposeForwardRequest
	12, // 29: wavespan.v1.CollectionService.SAdd:output_type -> wavespan.v1.CountResult
	12, // 30: wavespan.v1.CollectionService.SRem:output_type -> wavespan.v1.CountResult
	13, // 31: wavespan.v1.CollectionService.SIsMember:output_type -> wavespan.v1.BoolResult
	12, // 32: wavespan.v1.CollectionService.SCard:output_type -> wavespan.v1.CountResult
	16, // 33: wavespan.v1.CollectionService.SMembers:output_type -> wavespan.v1.MembersResult
	12, // 34: wavespan.v1.CollectionService.HSet:output_type -> wavespan.v1.CountResult
	12, // 35: wavespan.v1.CollectionService.HDel:output_type -> wavespan.v1.CountResult
	14, // 36: wavespan.v1.CollectionService.HGet:output_type -> wavespan.v1.ValueResult
	12, // 37: wavespan.v1.CollectionService.HLen:output_type -> wavespan.v1.CountResult
	17, // 38: wavespan.v1.CollectionService.HGetAll:output_type -> wavespan.v1.FieldsResult
	12, // 39: wavespan.v1.CollectionService.ZAdd:output_type -> wavespan.v1.CountResult
	12, // 40: wavespan.v1.CollectionService.ZRem:output_type -> wavespan.v1.CountResult
	15, // 41: wavespan.v1.CollectionService.ZScore:output_type -> wavespan.v1.ScoreResult
	12, // 42: wavespan.v1.CollectionService.ZCard:output_type -> wavespan.v1.CountResult
	18, // 43: wavespan.v1.CollectionService.ZRange:output_type -> wavespan.v1.ScoredMembersResult
	2,  // 44: wavespan.v1.CollectionService.AdmitLearner:output_type -> wavespan.v1.AdmitLearnerResponse
	12, // 45: wavespan.v1.CollectionService.ProposeForward:output_type -> wavespan.v1.CountResult
	29, // [29:46] is the sub-list for method output_type
	12, // [12:29] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_wavespan_v1_collections_proto_init() }
func file_wavespan_v1_collections_proto_init() {
	if File_wavespan_v1_collections_proto != nil {
		return
	}
	file_wavespan_v1_common_proto_init()
	file_wavespan_v1_collections_proto_msgTypes[5].OneofWrappers = []any{}
	file_wavespan_v1_collections_proto_msgTypes[6].OneofWrappers = []any{}
	file_wavespan_v1_collections_proto_msgTypes[10].OneofWrappers = []any{}
	file_wavespan_v1_collections_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wavespan_v1_collections_proto_rawDesc), len(file_wavespan_v1_collections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wavespan_v1_collections_proto_goTypes,
		DependencyIndexes: file_wavespan_v1_collections_proto_depIdxs,
		MessageInfos:      file_wavespan_v1_collections_proto_msgTypes,
	}.Build()
	File_wavespan_v1_collections_proto = out.File
	file_wavespan_v1_collections_proto_goTypes = nil
	file_wavespan_v1_collections_proto_depIdxs = nil
}
