// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wavespan/v1/common.proto

package wavespanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConflictState int32

const (
	ConflictState_CONFLICT_STATE_UNSPECIFIED ConflictState = 0
	ConflictState_CONFLICT_NONE              ConflictState = 1
	ConflictState_CONFLICT_RESOLVED          ConflictState = 2
	ConflictState_CONFLICT_SIBLINGS_PRESENT  ConflictState = 3
)

// Enum value maps for ConflictState.
var (
	ConflictState_name = map[int32]string{
		0: "CONFLICT_STATE_UNSPECIFIED",
		1: "CONFLICT_NONE",
		2: "CONFLICT_RESOLVED",
		3: "CONFLICT_SIBLINGS_PRESENT",
	}
	ConflictState_value = map[string]int32{
		"CONFLICT_STATE_UNSPECIFIED": 0,
		"CONFLICT_NONE":              1,
		"CONFLICT_RESOLVED":          2,
		"CONFLICT_SIBLINGS_PRESENT":  3,
	}
)

func (x ConflictState) Enum() *ConflictState {
	p := new(ConflictState)
	*p = x
	return p
}

func (x ConflictState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictState) Descriptor() protoreflect.EnumDescriptor {
	return file_wavespan_v1_common_proto_enumTypes[0].Descriptor()
}

func (ConflictState) Type() protoreflect.EnumType {
	return &file_wavespan_v1_common_proto_enumTypes[0]
}

func (x ConflictState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictState.Descriptor instead.
func (ConflictState) EnumDescriptor() ([]byte, []int) {
	return file_wavespan_v1_common_proto_rawDescGZIP(), []int{0}
}

type Completeness int32

const (
	Completeness_COMPLETENESS_UNSPECIFIED Completeness = 0
	Completeness_COMPLETE                 Completeness = 1
	Completeness_PARTIAL                  Completeness = 2
	Completeness_BEST_EFFORT              Completeness = 3
)

// Enum value maps for Completeness.
var (
	Completeness_name = map[int32]string{
		0: "COMPLETENESS_UNSPECIFIED",
		1: "COMPLETE",
		2: "PARTIAL",
		3: "BEST_EFFORT",
	}
	Completeness_value = map[string]int32{
		"COMPLETENESS_UNSPECIFIED": 0,
		"COMPLETE":                 1,
		"PARTIAL":                  2,
		"BEST_EFFORT":              3,
	}
)

func (x Completeness) Enum() *Completeness {
	p := new(Completeness)
	*p = x
	return p
}

func (x Completeness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Completeness) Descriptor() protoreflect.EnumDescriptor {
	return file_wavespan_v1_common_proto_enumTypes[1].Descriptor()
}

func (Completeness) Type() protoreflect.EnumType {
	return &file_wavespan_v1_common_proto_enumTypes[1]
}

func (x Completeness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Completeness.Descriptor instead.
func (Completeness) EnumDescriptor() ([]byte, []int) {
	return file_wavespan_v1_common_proto_rawDescGZIP(), []int{1}
}

type ReadSource int32

const (
	ReadSource_READ_SOURCE_UNSPECIFIED ReadSource = 0
	ReadSource_LOCAL_DURABLE           ReadSource = 1
	ReadSource_LOCAL_DYNAMIC_CACHE     ReadSource = 2
	ReadSource_FETCHED_CLOSEST_HOLDER  ReadSource = 3
	ReadSource_ROUTED_RANGE            ReadSource = 4
	ReadSource_GLOBAL_REMOTE           ReadSource = 5
)

// Enum value maps for ReadSource.
var (
	ReadSource_name = map[int32]string{
		0: "READ_SOURCE_UNSPECIFIED",
		1: "LOCAL_DURABLE",
		2: "LOCAL_DYNAMIC_CACHE",
		3: "FETCHED_CLOSEST_HOLDER",
		4: "ROUTED_RANGE",
		5: "GLOBAL_REMOTE",
	}
	ReadSource_value = map[string]int32{
		"READ_SOURCE_UNSPECIFIED": 0,
		"LOCAL_DURABLE":           1,
		"LOCAL_DYNAMIC_CACHE":     2,
		"FETCHED_CLOSEST_HOLDER":  3,
		"ROUTED_RANGE":            4,
		"GLOBAL_REMOTE":           5,
	}
)

func (x ReadSource) Enum() *ReadSource {
	p := new(ReadSource)
	*p = x
	return p
}

func (x ReadSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadSource) Descriptor() protoreflect.EnumDescriptor {
	return file_wavespan_v1_common_proto_enumTypes[2].Descriptor()
}

func (ReadSource) Type() protoreflect.EnumType {
	return &file_wavespan_v1_common_proto_enumTypes[2]
}

func (x ReadSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadSource.Descriptor instead.
func (ReadSource) EnumDescriptor() ([]byte, []int) {
	return file_wavespan_v1_common_proto_rawDescGZIP(), []int{2}
}

// Version is the per-mutation hybrid-logical-clock version stamped by the writing
// coordinator. See design/22_versioning_and_hlc.md and design/03_kv_store.md
// "Conflict handling" for the deterministic tie-break order.
type Version struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HlcPhysicalMs   uint64                 `protobuf:"varint,1,opt,name=hlc_physical_ms,json=hlcPhysicalMs,proto3" json:"hlc_physical_ms,omitempty"`
	HlcLogical      uint32                 `protobuf:"varint,2,opt,name=hlc_logical,json=hlcLogical,proto3" json:"hlc_logical,omitempty"`
	WriterClusterId string                 `protobuf:"bytes,3,opt,name=writer_cluster_id,json=writerClusterId,proto3" json:"writer_cluster_id,omitempty"`
	WriterMemberId  string                 `protobuf:"bytes,4,opt,name=writer_member_id,json=writerMemberId,proto3" json:"writer_member_id,omitempty"`
	WriterSequence  uint64                 `protobuf:"varint,5,opt,name=writer_sequence,json=writerSequence,proto3" json:"writer_sequence,omitempty"`
	VectorClock     []byte                 `protobuf:"bytes,6,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_wavespan_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetHlcPhysicalMs() uint64 {
	if x != nil {
		return x.HlcPhysicalMs
	}
	return 0
}

func (x *Version) GetHlcLogical() uint32 {
	if x != nil {
		return x.HlcLogical
	}
	return 0
}

func (x *Version) GetWriterClusterId() string {
	if x != nil {
		return x.WriterClusterId
	}
	return ""
}

func (x *Version) GetWriterMemberId() string {
	if x != nil {
		return x.WriterMemberId
	}
	return ""
}

func (x *Version) GetWriterSequence() uint64 {
	if x != nil {
		return x.WriterSequence
	}
	return 0
}

func (x *Version) GetVectorClock() []byte {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// MutationId is a stable, idempotent identifier for a logical mutation. It is derived
// from (writer_cluster_id, writer_member_id, writer_sequence) or, when the client
// supplies an idempotency key, from that key. Equal ids collapse retries into one
// logical mutation.
type MutationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationId) Reset() {
	*x = MutationId{}
	mi := &file_wavespan_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationId) ProtoMessage() {}

func (x *MutationId) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationId.ProtoReflect.Descriptor instead.
func (*MutationId) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *MutationId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ResponseMeta is attached to every user-visible read so the declared consistency
// and completeness mode is never hidden (design/01_architecture.md "Design constraints").
type ResponseMeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServedByClusterId string                 `protobuf:"bytes,1,opt,name=served_by_cluster_id,json=servedByClusterId,proto3" json:"served_by_cluster_id,omitempty"`
	ServedByMemberId  string                 `protobuf:"bytes,2,opt,name=served_by_member_id,json=servedByMemberId,proto3" json:"served_by_member_id,omitempty"`
	Source            ReadSource             `protobuf:"varint,3,opt,name=source,proto3,enum=wavespan.v1.ReadSource" json:"source,omitempty"`
	ObservedVersion   *Version               `protobuf:"bytes,4,opt,name=observed_version,json=observedVersion,proto3,oneof" json:"observed_version,omitempty"`
	ConflictState     ConflictState          `protobuf:"varint,5,opt,name=conflict_state,json=conflictState,proto3,enum=wavespan.v1.ConflictState" json:"conflict_state,omitempty"`
	Completeness      Completeness           `protobuf:"varint,6,opt,name=completeness,proto3,enum=wavespan.v1.Completeness" json:"completeness,omitempty"`
	ObservedAtUnixMs  int64                  `protobuf:"varint,7,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	Warnings          []string               `protobuf:"bytes,8,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	mi := &file_wavespan_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseMeta) GetServedByClusterId() string {
	if x != nil {
		return x.ServedByClusterId
	}
	return ""
}

func (x *ResponseMeta) GetServedByMemberId() string {
	if x != nil {
		return x.ServedByMemberId
	}
	return ""
}

func (x *ResponseMeta) GetSource() ReadSource {
	if x != nil {
		return x.Source
	}
	return ReadSource_READ_SOURCE_UNSPECIFIED
}

func (x *ResponseMeta) GetObservedVersion() *Version {
	if x != nil {
		return x.ObservedVersion
	}
	return nil
}

func (x *ResponseMeta) GetConflictState() ConflictState {
	if x != nil {
		return x.ConflictState
	}
	return ConflictState_CONFLICT_STATE_UNSPECIFIED
}

func (x *ResponseMeta) GetCompleteness() Completeness {
	if x != nil {
		return x.Completeness
	}
	return Completeness_COMPLETENESS_UNSPECIFIED
}

func (x *ResponseMeta) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

func (x *ResponseMeta) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_wavespan_v1_common_proto protoreflect.FileDescriptor

const file_wavespan_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18wavespan/v1/common.proto\x12\vwavespan.v1\"\xf4\x01\n" +
	"\aVersion\x12&\n" +
	"\x0fhlc_physical_ms\x18\x01 \x01(\x04R\rhlcPhysicalMs\x12\x1f\n" +
	"\vhlc_logical\x18\x02 \x01(\rR\n" +
	"hlcLogical\x12*\n" +
	"\x11writer_cluster_id\x18\x03 \x01(\tR\x0fwriterClusterId\x12(\n" +
	"\x10writer_member_id\x18\x04 \x01(\tR\x0ewriterMemberId\x12'\n" +
	"\x0fwriter_sequence\x18\x05 \x01(\x04R\x0ewriterSequence\x12!\n" +
	"\fvector_clock\x18\x06 \x01(\fR\vvectorClock\"\"\n" +
	"\n" +
	"MutationId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xc7\x03\n" +
	"\fResponseMeta\x12/\n" +
	"\x14served_by_cluster_id\x18\x01 \x01(\tR\x11servedByClusterId\x12-\n" +
	"\x13served_by_member_id\x18\x02 \x01(\tR\x10servedByMemberId\x12/\n" +
	"\x06source\x18\x03 \x01(\x0e2\x17.wavespan.v1.ReadSourceR\x06source\x12D\n" +
	"\x10observed_version\x18\x04 \x01(\v2\x14.wavespan.v1.VersionH\x00R\x0fobservedVersion\x88\x01\x01\x12A\n" +
	"\x0econflict_state\x18\x05 \x01(\x0e2\x1a.wavespan.v1.ConflictStateR\rconflictState\x12=\n" +
	"\fcompleteness\x18\x06 \x01(\x0e2\x19.wavespan.v1.CompletenessR\fcompleteness\x12-\n" +
	"\x13observed_at_unix_ms\x18\a \x01(\x03R\x10observedAtUnixMs\x12\x1a\n" +
	"\bwarnings\x18\b \x03(\tR\bwarningsB\x13\n" +
	"\x11_observed_version*x\n" +
	"\rConflictState\x12\x1e\n" +
	"\x1aCONFLICT_STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCONFLICT_NONE\x10\x01\x12\x15\n" +
	"\x11CONFLICT_RESOLVED\x10\x02\x12\x1d\n" +
	"\x19CONFLICT_SIBLINGS_PRESENT\x10\x03*X\n" +
	"\fCompleteness\x12\x1c\n" +
	"\x18COMPLETENESS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCOMPLETE\x10\x01\x12\v\n" +
	"\aPARTIAL\x10\x02\x12\x0f\n" +
	"\vBEST_EFFORT\x10\x03*\x96\x01\n" +
	"\n" +
	"ReadSource\x12\x1b\n" +
	"\x17READ_SOURCE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rLOCAL_DURABLE\x10\x01\x12\x17\n" +
	"\x13LOCAL_DYNAMIC_CACHE\x10\x02\x12\x1a\n" +
	"\x16FETCHED_CLOSEST_HOLDER\x10\x03\x12\x10\n" +
	"\fROUTED_RANGE\x10\x04\x12\x11\n" +
	"\rGLOBAL_REMOTE\x10\x05B\xa3\x01\n" +
	"\x0fcom.wavespan.v1B\vCommonProtoP\x01Z6github.com/cwire/wavespan/proto/wavespan/v1;wavespanv1\xa2\x02\x03WXX\xaa\x02\vWavespan.V1\xca\x02\vWavespan\\V1\xe2\x02\x17Wavespan\\V1\\GPBMetadata\xea\x02\fWavespan::V1b\x06proto3"

var (
	file_wavespan_v1_common_proto_rawDescOnce sync.Once
	file_wavespan_v1_common_proto_rawDescData []byte
)

func file_wavespan_v1_common_proto_rawDescGZIP() []byte {
	file_wavespan_v1_common_proto_rawDescOnce.Do(func() {
		file_wavespan_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wavespan_v1_common_proto_rawDesc), len(file_wavespan_v1_common_proto_rawDesc)))
	})
	return file_wavespan_v1_common_proto_rawDescData
}

var file_wavespan_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wavespan_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wavespan_v1_common_proto_goTypes = []any{
	(ConflictState)(0),   // 0: wavespan.v1.ConflictState
	(Completeness)(0),    // 1: wavespan.v1.Completeness
	(ReadSource)(0),      // 2: wavespan.v1.ReadSource
	(*Version)(nil),      // 3: wavespan.v1.Version
	(*MutationId)(nil),   // 4: wavespan.v1.MutationId
	(*ResponseMeta)(nil), // 5: wavespan.v1.ResponseMeta
}
var file_wavespan_v1_common_proto_depIdxs = []int32{
	2, // 0: wavespan.v1.ResponseMeta.source:type_name -> wavespan.v1.ReadSource
	3, // 1: wavespan.v1.ResponseMeta.observed_version:type_name -> wavespan.v1.Version
	0, // 2: wavespan.v1.ResponseMeta.conflict_state:type_name -> wavespan.v1.ConflictState
	1, // 3: wavespan.v1.ResponseMeta.completeness:type_name -> wavespan.v1.Completeness
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wavespan_v1_common_proto_init() }
func file_wavespan_v1_common_proto_init() {
	if File_wavespan_v1_common_proto != nil {
		return
	}
	file_wavespan_v1_common_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wavespan_v1_common_proto_rawDesc), len(file_wavespan_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wavespan_v1_common_proto_goTypes,
		DependencyIndexes: file_wavespan_v1_common_proto_depIdxs,
		EnumInfos:         file_wavespan_v1_common_proto_enumTypes,
		MessageInfos:      file_wavespan_v1_common_proto_msgTypes,
	}.Build()
	File_wavespan_v1_common_proto = out.File
	file_wavespan_v1_common_proto_goTypes = nil
	file_wavespan_v1_common_proto_depIdxs = nil
}
