// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wavespan/v1/kv.proto

package wavespanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlMs     *int64                 `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3,oneof" json:"ttl_ms,omitempty"`
	// idempotency_key: a retry with the same key collapses to one logical mutation.
	IdempotencyKey *string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	// require_origin_plus_one defaults true; the write ACKs only after a nearby durable replica.
	RequireOriginPlusOne bool `protobuf:"varint,6,opt,name=require_origin_plus_one,json=requireOriginPlusOne,proto3" json:"require_origin_plus_one,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_wavespan_v1_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_kv_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetTtlMs() int64 {
	if x != nil && x.TtlMs != nil {
		return *x.TtlMs
	}
	return 0
}

func (x *PutRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *PutRequest) GetRequireOriginPlusOne() bool {
	if x != nil {
		return x.RequireOriginPlusOne
	}
	return false
}

type PutResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Meta                *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Version             *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	AckedNearbyReplicas uint32                 `protobuf:"varint,3,opt,name=acked_nearby_replicas,json=ackedNearbyReplicas,proto3" json:"acked_nearby_replicas,omitempty"`
	GeoSpillover        bool                   `protobuf:"varint,4,opt,name=geo_spillover,json=geoSpillover,proto3" json:"geo_spillover,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PutResult) Reset() {
	*x = PutResult{}
	mi := &file_wavespan_v1_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResult) ProtoMessage() {}

func (x *PutResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResult.ProtoReflect.Descriptor instead.
func (*PutResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_kv_proto_rawDescGZIP(), []int{1}
}

func (x *PutResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PutResult) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *PutResult) GetAckedNearbyReplicas() uint32 {
	if x != nil {
		return x.AckedNearbyReplicas
	}
	return 0
}

func (x *PutResult) GetGeoSpillover() bool {
	if x != nil {
		return x.GeoSpillover
	}
	return false
}

type GetRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Namespace         string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key               []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	AllowDynamicCache bool                   `protobuf:"varint,3,opt,name=allow_dynamic_cache,json=allowDynamicCache,proto3" json:"allow_dynamic_cache,omitempty"` // default true; cache path lands at M5
	HideExpiredOnRead bool                   `protobuf:"varint,4,opt,name=hide_expired_on_read,json=hideExpiredOnRead,proto3" json:"hide_expired_on_read,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_wavespan_v1_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetAllowDynamicCache() bool {
	if x != nil {
		return x.AllowDynamicCache
	}
	return false
}

func (x *GetRequest) GetHideExpiredOnRead() bool {
	if x != nil {
		return x.HideExpiredOnRead
	}
	return false
}

type GetResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Found           bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Value           []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAtUnixMs *int64                 `protobuf:"varint,4,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3,oneof" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetResult) Reset() {
	*x = GetResult{}
	mi := &file_wavespan_v1_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResult) ProtoMessage() {}

func (x *GetResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResult.ProtoReflect.Descriptor instead.
func (*GetResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResult) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResult) GetExpiresAtUnixMs() int64 {
	if x != nil && x.ExpiresAtUnixMs != nil {
		return *x.ExpiresAtUnixMs
	}
	return 0
}

type DeleteRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Namespace            string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	IdempotencyKey       *string                `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	RequireOriginPlusOne bool                   `protobuf:"varint,4,opt,name=require_origin_plus_one,json=requireOriginPlusOne,proto3" json:"require_origin_plus_one,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_wavespan_v1_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *DeleteRequest) GetRequireOriginPlusOne() bool {
	if x != nil {
		return x.RequireOriginPlusOne
	}
	return false
}

type DeleteResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Meta                *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Version             *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	AckedNearbyReplicas uint32                 `protobuf:"varint,3,opt,name=acked_nearby_replicas,json=ackedNearbyReplicas,proto3" json:"acked_nearby_replicas,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_wavespan_v1_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResult) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DeleteResult) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DeleteResult) GetAckedNearbyReplicas() uint32 {
	if x != nil {
		return x.AckedNearbyReplicas
	}
	return 0
}

// ScanHeader is the first message of a range scan stream (design/03 "Range scans"). The Scan
// RPC and its body land at M6; the header is defined here so the wire shape is stable.
type ScanHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Completeness  Completeness           `protobuf:"varint,2,opt,name=completeness,proto3,enum=wavespan.v1.Completeness" json:"completeness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanHeader) Reset() {
	*x = ScanHeader{}
	mi := &file_wavespan_v1_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanHeader) ProtoMessage() {}

func (x *ScanHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanHeader.ProtoReflect.Descriptor instead.
func (*ScanHeader) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_kv_proto_rawDescGZIP(), []int{6}
}

func (x *ScanHeader) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ScanHeader) GetCompleteness() Completeness {
	if x != nil {
		return x.Completeness
	}
	return Completeness_COMPLETENESS_UNSPECIFIED
}

var File_wavespan_v1_kv_proto protoreflect.FileDescriptor

const file_wavespan_v1_kv_proto_rawDesc = "" +
	"\n" +
	"\x14wavespan/v1/kv.proto\x12\vwavespan.v1\x1a\x18wavespan/v1/common.proto\"\xf2\x01\n" +
	"\n" +
	"PutRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1a\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03H\x00R\x05ttlMs\x88\x01\x01\x12,\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tH\x01R\x0eidempotencyKey\x88\x01\x01\x125\n" +
	"\x17require_origin_plus_one\x18\x06 \x01(\bR\x14requireOriginPlusOneB\t\n" +
	"\a_ttl_msB\x12\n" +
	"\x10_idempotency_key\"\xc3\x01\n" +
	"\tPutResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12.\n" +
	"\aversion\x18\x02 \x01(\v2\x14.wavespan.v1.VersionR\aversion\x122\n" +
	"\x15acked_nearby_replicas\x18\x03 \x01(\rR\x13ackedNearbyReplicas\x12#\n" +
	"\rgeo_spillover\x18\x04 \x01(\bR\fgeoSpillover\"\x9d\x01\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12.\n" +
	"\x13allow_dynamic_cache\x18\x03 \x01(\bR\x11allowDynamicCache\x12/\n" +
	"\x14hide_expired_on_read\x18\x04 \x01(\bR\x11hideExpiredOnRead\"\xaf\x01\n" +
	"\tGetResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x120\n" +
	"\x12expires_at_unix_ms\x18\x04 \x01(\x03H\x00R\x0fexpiresAtUnixMs\x88\x01\x01B\x15\n" +
	"\x13_expires_at_unix_ms\"\xb8\x01\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12,\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01\x125\n" +
	"\x17require_origin_plus_one\x18\x04 \x01(\bR\x14requireOriginPlusOneB\x12\n" +
	"\x10_idempotency_key\"\xa1\x01\n" +
	"\fDeleteResult\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12.\n" +
	"\aversion\x18\x02 \x01(\v2\x14.wavespan.v1.VersionR\aversion\x122\n" +
	"\x15acked_nearby_replicas\x18\x03 \x01(\rR\x13ackedNearbyReplicas\"z\n" +
	"\n" +
	"ScanHeader\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.wavespan.v1.ResponseMetaR\x04meta\x12=\n" +
	"\fcompleteness\x18\x02 \x01(\x0e2\x19.wavespan.v1.CompletenessR\fcompleteness2\xbc\x01\n" +
	"\tKvService\x126\n" +
	"\x03Put\x12\x17.wavespan.v1.PutRequest\x1a\x16.wavespan.v1.PutResult\x126\n" +
	"\x03Get\x12\x17.wavespan.v1.GetRequest\x1a\x16.wavespan.v1.GetResult\x12?\n" +
	"\x06Delete\x12\x1a.wavespan.v1.DeleteRequest\x1a\x19.wavespan.v1.DeleteResultB\x9f\x01\n" +
	"\x0fcom.wavespan.v1B\aKvProtoP\x01Z6github.com/cwire/wavespan/proto/wavespan/v1;wavespanv1\xa2\x02\x03WXX\xaa\x02\vWavespan.V1\xca\x02\vWavespan\\V1\xe2\x02\x17Wavespan\\V1\\GPBMetadata\xea\x02\fWavespan::V1b\x06proto3"

var (
	file_wavespan_v1_kv_proto_rawDescOnce sync.Once
	file_wavespan_v1_kv_proto_rawDescData []byte
)

func file_wavespan_v1_kv_proto_rawDescGZIP() []byte {
	file_wavespan_v1_kv_proto_rawDescOnce.Do(func() {
		file_wavespan_v1_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wavespan_v1_kv_proto_rawDesc), len(file_wavespan_v1_kv_proto_rawDesc)))
	})
	return file_wavespan_v1_kv_proto_rawDescData
}

var file_wavespan_v1_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wavespan_v1_kv_proto_goTypes = []any{
	(*PutRequest)(nil),    // 0: wavespan.v1.PutRequest
	(*PutResult)(nil),     // 1: wavespan.v1.PutResult
	(*GetRequest)(nil),    // 2: wavespan.v1.GetRequest
	(*GetResult)(nil),     // 3: wavespan.v1.GetResult
	(*DeleteRequest)(nil), // 4: wavespan.v1.DeleteRequest
	(*DeleteResult)(nil),  // 5: wavespan.v1.DeleteResult
	(*ScanHeader)(nil),    // 6: wavespan.v1.ScanHeader
	(*ResponseMeta)(nil),  // 7: wavespan.v1.ResponseMeta
	(*Version)(nil),       // 8: wavespan.v1.Version
	(Completeness)(0),     // 9: wavespan.v1.Completeness
}
var file_wavespan_v1_kv_proto_depIdxs = []int32{
	7,  // 0: wavespan.v1.PutResult.meta:type_name -> wavespan.v1.ResponseMeta
	8,  // 1: wavespan.v1.PutResult.version:type_name -> wavespan.v1.Version
	7,  // 2: wavespan.v1.GetResult.meta:type_name -> wavespan.v1.ResponseMeta
	7,  // 3: wavespan.v1.DeleteResult.meta:type_name -> wavespan.v1.ResponseMeta
	8,  // 4: wavespan.v1.DeleteResult.version:type_name -> wavespan.v1.Version
	7,  // 5: wavespan.v1.ScanHeader.meta:type_name -> wavespan.v1.ResponseMeta
	9,  // 6: wavespan.v1.ScanHeader.completeness:type_name -> wavespan.v1.Completeness
	0,  // 7: wavespan.v1.KvService.Put:input_type -> wavespan.v1.PutRequest
	2,  // 8: wavespan.v1.KvService.Get:input_type -> wavespan.v1.GetRequest
	4,  // 9: wavespan.v1.KvService.Delete:input_type -> wavespan.v1.DeleteRequest
	1,  // 10: wavespan.v1.KvService.Put:output_type -> wavespan.v1.PutResult
	3,  // 11: wavespan.v1.KvService.Get:output_type -> wavespan.v1.GetResult
	5,  // 12: wavespan.v1.KvService.Delete:output_type -> wavespan.v1.DeleteResult
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_wavespan_v1_kv_proto_init() }
func file_wavespan_v1_kv_proto_init() {
	if File_wavespan_v1_kv_proto != nil {
		return
	}
	file_wavespan_v1_common_proto_init()
	file_wavespan_v1_kv_proto_msgTypes[0].OneofWrappers = []any{}
	file_wavespan_v1_kv_proto_msgTypes[3].OneofWrappers = []any{}
	file_wavespan_v1_kv_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wavespan_v1_kv_proto_rawDesc), len(file_wavespan_v1_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wavespan_v1_kv_proto_goTypes,
		DependencyIndexes: file_wavespan_v1_kv_proto_depIdxs,
		MessageInfos:      file_wavespan_v1_kv_proto_msgTypes,
	}.Build()
	File_wavespan_v1_kv_proto = out.File
	file_wavespan_v1_kv_proto_goTypes = nil
	file_wavespan_v1_kv_proto_depIdxs = nil
}
