// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wavespan/v1/replication.proto

package wavespanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReplicaClass distinguishes durable replicas (counted for write durability) from disposable
// dynamic-cache copies (design/05 replica types).
type ReplicaClass int32

const (
	ReplicaClass_REPLICA_CLASS_UNSPECIFIED    ReplicaClass = 0
	ReplicaClass_REPLICA_CLASS_NEARBY_DURABLE ReplicaClass = 1
	ReplicaClass_REPLICA_CLASS_DYNAMIC_CACHE  ReplicaClass = 2
)

// Enum value maps for ReplicaClass.
var (
	ReplicaClass_name = map[int32]string{
		0: "REPLICA_CLASS_UNSPECIFIED",
		1: "REPLICA_CLASS_NEARBY_DURABLE",
		2: "REPLICA_CLASS_DYNAMIC_CACHE",
	}
	ReplicaClass_value = map[string]int32{
		"REPLICA_CLASS_UNSPECIFIED":    0,
		"REPLICA_CLASS_NEARBY_DURABLE": 1,
		"REPLICA_CLASS_DYNAMIC_CACHE":  2,
	}
)

func (x ReplicaClass) Enum() *ReplicaClass {
	p := new(ReplicaClass)
	*p = x
	return p
}

func (x ReplicaClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicaClass) Descriptor() protoreflect.EnumDescriptor {
	return file_wavespan_v1_replication_proto_enumTypes[0].Descriptor()
}

func (ReplicaClass) Type() protoreflect.EnumType {
	return &file_wavespan_v1_replication_proto_enumTypes[0]
}

func (x ReplicaClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicaClass.Descriptor instead.
func (ReplicaClass) EnumDescriptor() ([]byte, []int) {
	return file_wavespan_v1_replication_proto_rawDescGZIP(), []int{0}
}

// StoreReplicaRequest carries a versioned record to a nearby peer for durable replication
// (design/05 "StoreReplica protocol").
type StoreReplicaRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Namespace           string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                 []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Record              *StoredRecord          `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	ReplicaClass        ReplicaClass           `protobuf:"varint,4,opt,name=replica_class,json=replicaClass,proto3,enum=wavespan.v1.ReplicaClass" json:"replica_class,omitempty"`
	CoordinatorMemberId string                 `protobuf:"bytes,5,opt,name=coordinator_member_id,json=coordinatorMemberId,proto3" json:"coordinator_member_id,omitempty"`
	MutationId          string                 `protobuf:"bytes,6,opt,name=mutation_id,json=mutationId,proto3" json:"mutation_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StoreReplicaRequest) Reset() {
	*x = StoreReplicaRequest{}
	mi := &file_wavespan_v1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReplicaRequest) ProtoMessage() {}

func (x *StoreReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReplicaRequest.ProtoReflect.Descriptor instead.
func (*StoreReplicaRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *StoreReplicaRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StoreReplicaRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoreReplicaRequest) GetRecord() *StoredRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *StoreReplicaRequest) GetReplicaClass() ReplicaClass {
	if x != nil {
		return x.ReplicaClass
	}
	return ReplicaClass_REPLICA_CLASS_UNSPECIFIED
}

func (x *StoreReplicaRequest) GetCoordinatorMemberId() string {
	if x != nil {
		return x.CoordinatorMemberId
	}
	return ""
}

func (x *StoreReplicaRequest) GetMutationId() string {
	if x != nil {
		return x.MutationId
	}
	return ""
}

type StoreReplicaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Durable        bool                   `protobuf:"varint,1,opt,name=durable,proto3" json:"durable,omitempty"`
	MemberId       string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	AppliedVersion *Version               `protobuf:"bytes,3,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	ConflictState  ConflictState          `protobuf:"varint,4,opt,name=conflict_state,json=conflictState,proto3,enum=wavespan.v1.ConflictState" json:"conflict_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreReplicaResponse) Reset() {
	*x = StoreReplicaResponse{}
	mi := &file_wavespan_v1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReplicaResponse) ProtoMessage() {}

func (x *StoreReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReplicaResponse.ProtoReflect.Descriptor instead.
func (*StoreReplicaResponse) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *StoreReplicaResponse) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *StoreReplicaResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *StoreReplicaResponse) GetAppliedVersion() *Version {
	if x != nil {
		return x.AppliedVersion
	}
	return nil
}

func (x *StoreReplicaResponse) GetConflictState() ConflictState {
	if x != nil {
		return x.ConflictState
	}
	return ConflictState_CONFLICT_STATE_UNSPECIFIED
}

var File_wavespan_v1_replication_proto protoreflect.FileDescriptor

const file_wavespan_v1_replication_proto_rawDesc = "" +
	"\n" +
	"\x1dwavespan/v1/replication.proto\x12\vwavespan.v1\x1a\x18wavespan/v1/common.proto\"\x8d\x02\n" +
	"\x13StoreReplicaRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x121\n" +
	"\x06record\x18\x03 \x01(\v2\x19.wavespan.v1.StoredRecordR\x06record\x12>\n" +
	"\rreplica_class\x18\x04 \x01(\x0e2\x19.wavespan.v1.ReplicaClassR\freplicaClass\x122\n" +
	"\x15coordinator_member_id\x18\x05 \x01(\tR\x13coordinatorMemberId\x12\x1f\n" +
	"\vmutation_id\x18\x06 \x01(\tR\n" +
	"mutationId\"\xcf\x01\n" +
	"\x14StoreReplicaResponse\x12\x18\n" +
	"\adurable\x18\x01 \x01(\bR\adurable\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12=\n" +
	"\x0fapplied_version\x18\x03 \x01(\v2\x14.wavespan.v1.VersionR\x0eappliedVersion\x12A\n" +
	"\x0econflict_state\x18\x04 \x01(\x0e2\x1a.wavespan.v1.ConflictStateR\rconflictState*p\n" +
	"\fReplicaClass\x12\x1d\n" +
	"\x19REPLICA_CLASS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cREPLICA_CLASS_NEARBY_DURABLE\x10\x01\x12\x1f\n" +
	"\x1bREPLICA_CLASS_DYNAMIC_CACHE\x10\x022i\n" +
	"\x12ReplicationService\x12S\n" +
	"\fStoreReplica\x12 .wavespan.v1.StoreReplicaRequest\x1a!.wavespan.v1.StoreReplicaResponseB\xa8\x01\n" +
	"\x0fcom.wavespan.v1B\x10ReplicationProtoP\x01Z6github.com/cwire/wavespan/proto/wavespan/v1;wavespanv1\xa2\x02\x03WXX\xaa\x02\vWavespan.V1\xca\x02\vWavespan\\V1\xe2\x02\x17Wavespan\\V1\\GPBMetadata\xea\x02\fWavespan::V1b\x06proto3"

var (
	file_wavespan_v1_replication_proto_rawDescOnce sync.Once
	file_wavespan_v1_replication_proto_rawDescData []byte
)

func file_wavespan_v1_replication_proto_rawDescGZIP() []byte {
	file_wavespan_v1_replication_proto_rawDescOnce.Do(func() {
		file_wavespan_v1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wavespan_v1_replication_proto_rawDesc), len(file_wavespan_v1_replication_proto_rawDesc)))
	})
	return file_wavespan_v1_replication_proto_rawDescData
}

var file_wavespan_v1_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wavespan_v1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wavespan_v1_replication_proto_goTypes = []any{
	(ReplicaClass)(0),            // 0: wavespan.v1.ReplicaClass
	(*StoreReplicaRequest)(nil),  // 1: wavespan.v1.StoreReplicaRequest
	(*StoreReplicaResponse)(nil), // 2: wavespan.v1.StoreReplicaResponse
	(*StoredRecord)(nil),         // 3: wavespan.v1.StoredRecord
	(*Version)(nil),              // 4: wavespan.v1.Version
	(ConflictState)(0),           // 5: wavespan.v1.ConflictState
}
var file_wavespan_v1_replication_proto_depIdxs = []int32{
	3, // 0: wavespan.v1.StoreReplicaRequest.record:type_name -> wavespan.v1.StoredRecord
	0, // 1: wavespan.v1.StoreReplicaRequest.replica_class:type_name -> wavespan.v1.ReplicaClass
	4, // 2: wavespan.v1.StoreReplicaResponse.applied_version:type_name -> wavespan.v1.Version
	5, // 3: wavespan.v1.StoreReplicaResponse.conflict_state:type_name -> wavespan.v1.ConflictState
	1, // 4: wavespan.v1.ReplicationService.StoreReplica:input_type -> wavespan.v1.StoreReplicaRequest
	2, // 5: wavespan.v1.ReplicationService.StoreReplica:output_type -> wavespan.v1.StoreReplicaResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wavespan_v1_replication_proto_init() }
func file_wavespan_v1_replication_proto_init() {
	if File_wavespan_v1_replication_proto != nil {
		return
	}
	file_wavespan_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wavespan_v1_replication_proto_rawDesc), len(file_wavespan_v1_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wavespan_v1_replication_proto_goTypes,
		DependencyIndexes: file_wavespan_v1_replication_proto_depIdxs,
		EnumInfos:         file_wavespan_v1_replication_proto_enumTypes,
		MessageInfos:      file_wavespan_v1_replication_proto_msgTypes,
	}.Build()
	File_wavespan_v1_replication_proto = out.File
	file_wavespan_v1_replication_proto_goTypes = nil
	file_wavespan_v1_replication_proto_depIdxs = nil
}
