// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wavespan/v1/vector.proto

package wavespanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VectorRecord is a raw embedding vector, optionally attached to a graph node (design/08
// "Vector record"). Stored in CFVectorRaw and versioned/replicated via the StoredRecord pipeline.
type VectorRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	VectorId      string                 `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	Values        []float32              `protobuf:"fixed32,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	Dtype         string                 `protobuf:"bytes,4,opt,name=dtype,proto3" json:"dtype,omitempty"` // "float32" in v1
	Dimensions    uint32                 `protobuf:"varint,5,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Metadata      map[string]*Value      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GraphNodeId   string                 `protobuf:"bytes,7,opt,name=graph_node_id,json=graphNodeId,proto3" json:"graph_node_id,omitempty"` // optional graph attachment
	Version       *Version               `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Tombstone     bool                   `protobuf:"varint,9,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorRecord) Reset() {
	*x = VectorRecord{}
	mi := &file_wavespan_v1_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRecord) ProtoMessage() {}

func (x *VectorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRecord.ProtoReflect.Descriptor instead.
func (*VectorRecord) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{0}
}

func (x *VectorRecord) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorRecord) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *VectorRecord) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *VectorRecord) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

func (x *VectorRecord) GetDimensions() uint32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *VectorRecord) GetMetadata() map[string]*Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VectorRecord) GetGraphNodeId() string {
	if x != nil {
		return x.GraphNodeId
	}
	return ""
}

func (x *VectorRecord) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *VectorRecord) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

// VectorMeta is the lightweight metadata record at /vector/{collection}/meta/{vector_id}.
type VectorMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	VectorId      string                 `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	Dimensions    uint32                 `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Metric        string                 `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	GraphNodeId   string                 `protobuf:"bytes,5,opt,name=graph_node_id,json=graphNodeId,proto3" json:"graph_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorMeta) Reset() {
	*x = VectorMeta{}
	mi := &file_wavespan_v1_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorMeta) ProtoMessage() {}

func (x *VectorMeta) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorMeta.ProtoReflect.Descriptor instead.
func (*VectorMeta) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{1}
}

func (x *VectorMeta) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorMeta) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *VectorMeta) GetDimensions() uint32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *VectorMeta) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *VectorMeta) GetGraphNodeId() string {
	if x != nil {
		return x.GraphNodeId
	}
	return ""
}

type PutVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *VectorRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutVectorRequest) Reset() {
	*x = PutVectorRequest{}
	mi := &file_wavespan_v1_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVectorRequest) ProtoMessage() {}

func (x *PutVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVectorRequest.ProtoReflect.Descriptor instead.
func (*PutVectorRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{2}
}

func (x *PutVectorRequest) GetRecord() *VectorRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type PutVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutVectorResponse) Reset() {
	*x = PutVectorResponse{}
	mi := &file_wavespan_v1_vector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVectorResponse) ProtoMessage() {}

func (x *PutVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVectorResponse.ProtoReflect.Descriptor instead.
func (*PutVectorResponse) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{3}
}

var File_wavespan_v1_vector_proto protoreflect.FileDescriptor

const file_wavespan_v1_vector_proto_rawDesc = "" +
	"\n" +
	"\x18wavespan/v1/vector.proto\x12\vwavespan.v1\x1a\x18wavespan/v1/common.proto\x1a\x18wavespan/v1/cypher.proto\"\xa1\x03\n" +
	"\fVectorRecord\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1b\n" +
	"\tvector_id\x18\x02 \x01(\tR\bvectorId\x12\x16\n" +
	"\x06values\x18\x03 \x03(\x02R\x06values\x12\x14\n" +
	"\x05dtype\x18\x04 \x01(\tR\x05dtype\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x05 \x01(\rR\n" +
	"dimensions\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.wavespan.v1.VectorRecord.MetadataEntryR\bmetadata\x12\"\n" +
	"\rgraph_node_id\x18\a \x01(\tR\vgraphNodeId\x12.\n" +
	"\aversion\x18\b \x01(\v2\x14.wavespan.v1.VersionR\aversion\x12\x1c\n" +
	"\ttombstone\x18\t \x01(\bR\ttombstone\x1aO\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.wavespan.v1.ValueR\x05value:\x028\x01\"\xa5\x01\n" +
	"\n" +
	"VectorMeta\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1b\n" +
	"\tvector_id\x18\x02 \x01(\tR\bvectorId\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\rR\n" +
	"dimensions\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\tR\x06metric\x12\"\n" +
	"\rgraph_node_id\x18\x05 \x01(\tR\vgraphNodeId\"E\n" +
	"\x10PutVectorRequest\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.wavespan.v1.VectorRecordR\x06record\"\x13\n" +
	"\x11PutVectorResponse2U\n" +
	"\rVectorService\x12D\n" +
	"\x03Put\x12\x1d.wavespan.v1.PutVectorRequest\x1a\x1e.wavespan.v1.PutVectorResponseB\xa3\x01\n" +
	"\x0fcom.wavespan.v1B\vVectorProtoP\x01Z6github.com/cwire/wavespan/proto/wavespan/v1;wavespanv1\xa2\x02\x03WXX\xaa\x02\vWavespan.V1\xca\x02\vWavespan\\V1\xe2\x02\x17Wavespan\\V1\\GPBMetadata\xea\x02\fWavespan::V1b\x06proto3"

var (
	file_wavespan_v1_vector_proto_rawDescOnce sync.Once
	file_wavespan_v1_vector_proto_rawDescData []byte
)

func file_wavespan_v1_vector_proto_rawDescGZIP() []byte {
	file_wavespan_v1_vector_proto_rawDescOnce.Do(func() {
		file_wavespan_v1_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wavespan_v1_vector_proto_rawDesc), len(file_wavespan_v1_vector_proto_rawDesc)))
	})
	return file_wavespan_v1_vector_proto_rawDescData
}

var file_wavespan_v1_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wavespan_v1_vector_proto_goTypes = []any{
	(*VectorRecord)(nil),      // 0: wavespan.v1.VectorRecord
	(*VectorMeta)(nil),        // 1: wavespan.v1.VectorMeta
	(*PutVectorRequest)(nil),  // 2: wavespan.v1.PutVectorRequest
	(*PutVectorResponse)(nil), // 3: wavespan.v1.PutVectorResponse
	nil,                       // 4: wavespan.v1.VectorRecord.MetadataEntry
	(*Version)(nil),           // 5: wavespan.v1.Version
	(*Value)(nil),             // 6: wavespan.v1.Value
}
var file_wavespan_v1_vector_proto_depIdxs = []int32{
	4, // 0: wavespan.v1.VectorRecord.metadata:type_name -> wavespan.v1.VectorRecord.MetadataEntry
	5, // 1: wavespan.v1.VectorRecord.version:type_name -> wavespan.v1.Version
	0, // 2: wavespan.v1.PutVectorRequest.record:type_name -> wavespan.v1.VectorRecord
	6, // 3: wavespan.v1.VectorRecord.MetadataEntry.value:type_name -> wavespan.v1.Value
	2, // 4: wavespan.v1.VectorService.Put:input_type -> wavespan.v1.PutVectorRequest
	3, // 5: wavespan.v1.VectorService.Put:output_type -> wavespan.v1.PutVectorResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wavespan_v1_vector_proto_init() }
func file_wavespan_v1_vector_proto_init() {
	if File_wavespan_v1_vector_proto != nil {
		return
	}
	file_wavespan_v1_common_proto_init()
	file_wavespan_v1_cypher_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wavespan_v1_vector_proto_rawDesc), len(file_wavespan_v1_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wavespan_v1_vector_proto_goTypes,
		DependencyIndexes: file_wavespan_v1_vector_proto_depIdxs,
		MessageInfos:      file_wavespan_v1_vector_proto_msgTypes,
	}.Build()
	File_wavespan_v1_vector_proto = out.File
	file_wavespan_v1_vector_proto_goTypes = nil
	file_wavespan_v1_vector_proto_depIdxs = nil
}
