// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: wavespan/v1/vector.proto

package wavespanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VectorRecord is a raw embedding vector, optionally attached to a graph node (design/08
// "Vector record"). Stored in CFVectorRaw and versioned/replicated via the StoredRecord pipeline.
type VectorRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection  string            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	VectorId    string            `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	Values      []float32         `protobuf:"fixed32,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	Dtype       string            `protobuf:"bytes,4,opt,name=dtype,proto3" json:"dtype,omitempty"` // "float32" in v1
	Dimensions  uint32            `protobuf:"varint,5,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Metadata    map[string]*Value `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	GraphNodeId string            `protobuf:"bytes,7,opt,name=graph_node_id,json=graphNodeId,proto3" json:"graph_node_id,omitempty"` // optional graph attachment
	Version     *Version          `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Tombstone   bool              `protobuf:"varint,9,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	Payload     []byte            `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"` // caller's opaque proto payload (vector-as-key value)
}

func (x *VectorRecord) Reset() {
	*x = VectorRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRecord) ProtoMessage() {}

func (x *VectorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRecord.ProtoReflect.Descriptor instead.
func (*VectorRecord) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{0}
}

func (x *VectorRecord) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorRecord) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *VectorRecord) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *VectorRecord) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

func (x *VectorRecord) GetDimensions() uint32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *VectorRecord) GetMetadata() map[string]*Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VectorRecord) GetGraphNodeId() string {
	if x != nil {
		return x.GraphNodeId
	}
	return ""
}

func (x *VectorRecord) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *VectorRecord) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *VectorRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// VectorMeta is the lightweight metadata record at /vector/{collection}/meta/{vector_id}.
type VectorMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection  string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	VectorId    string `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	Dimensions  uint32 `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Metric      string `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	GraphNodeId string `protobuf:"bytes,5,opt,name=graph_node_id,json=graphNodeId,proto3" json:"graph_node_id,omitempty"`
}

func (x *VectorMeta) Reset() {
	*x = VectorMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorMeta) ProtoMessage() {}

func (x *VectorMeta) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorMeta.ProtoReflect.Descriptor instead.
func (*VectorMeta) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{1}
}

func (x *VectorMeta) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorMeta) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *VectorMeta) GetDimensions() uint32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *VectorMeta) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *VectorMeta) GetGraphNodeId() string {
	if x != nil {
		return x.GraphNodeId
	}
	return ""
}

type PutVectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *VectorRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *PutVectorRequest) Reset() {
	*x = PutVectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVectorRequest) ProtoMessage() {}

func (x *PutVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVectorRequest.ProtoReflect.Descriptor instead.
func (*PutVectorRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{2}
}

func (x *PutVectorRequest) GetRecord() *VectorRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type PutVectorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutVectorResponse) Reset() {
	*x = PutVectorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVectorResponse) ProtoMessage() {}

func (x *PutVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVectorResponse.ProtoReflect.Descriptor instead.
func (*PutVectorResponse) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{3}
}

// SearchLocalRequest asks a node to search ONLY the vectors it holds locally and return its
// fragment of the top-k (design/08 "scatter to partition-holders"). The query coordinator merges
// fragments from every holder. exact=true scans the collection; otherwise the ANN live index is
// used with ef_search. Hits are exact-scored from the stored vector regardless, so the merged
// global top-k is exact over the candidate union.
type SearchLocalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexName string    `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Query     []float32 `protobuf:"fixed32,2,rep,packed,name=query,proto3" json:"query,omitempty"`
	K         int32     `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	EfSearch  int32     `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	Exact     bool      `protobuf:"varint,5,opt,name=exact,proto3" json:"exact,omitempty"`
	Rerank    bool      `protobuf:"varint,6,opt,name=rerank,proto3" json:"rerank,omitempty"` // over-fetch ANN candidates before exact scoring
}

func (x *SearchLocalRequest) Reset() {
	*x = SearchLocalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLocalRequest) ProtoMessage() {}

func (x *SearchLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLocalRequest.ProtoReflect.Descriptor instead.
func (*SearchLocalRequest) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{4}
}

func (x *SearchLocalRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *SearchLocalRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchLocalRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchLocalRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *SearchLocalRequest) GetExact() bool {
	if x != nil {
		return x.Exact
	}
	return false
}

func (x *SearchLocalRequest) GetRerank() bool {
	if x != nil {
		return x.Rerank
	}
	return false
}

// VectorHit is one local search result (exact-scored).
type VectorHit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection  string  `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	VectorId    string  `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	GraphNodeId string  `protobuf:"bytes,3,opt,name=graph_node_id,json=graphNodeId,proto3" json:"graph_node_id,omitempty"`
	Distance    float64 `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"` // smaller = closer (ranking)
	Score       float64 `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`       // larger = more similar (user-facing)
}

func (x *VectorHit) Reset() {
	*x = VectorHit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorHit) ProtoMessage() {}

func (x *VectorHit) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorHit.ProtoReflect.Descriptor instead.
func (*VectorHit) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{5}
}

func (x *VectorHit) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorHit) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *VectorHit) GetGraphNodeId() string {
	if x != nil {
		return x.GraphNodeId
	}
	return ""
}

func (x *VectorHit) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *VectorHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchLocalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hits []*VectorHit `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
}

func (x *SearchLocalResponse) Reset() {
	*x = SearchLocalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchLocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLocalResponse) ProtoMessage() {}

func (x *SearchLocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLocalResponse.ProtoReflect.Descriptor instead.
func (*SearchLocalResponse) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{6}
}

func (x *SearchLocalResponse) GetHits() []*VectorHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type VectorPutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection string    `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector     []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Payload    []byte    `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TtlMs      *int64    `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3,oneof" json:"ttl_ms,omitempty"` // reserved (TTL plumbing is a later phase)
}

func (x *VectorPutReq) Reset() {
	*x = VectorPutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorPutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorPutReq) ProtoMessage() {}

func (x *VectorPutReq) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorPutReq.ProtoReflect.Descriptor instead.
func (*VectorPutReq) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{7}
}

func (x *VectorPutReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorPutReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *VectorPutReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VectorPutReq) GetTtlMs() int64 {
	if x != nil && x.TtlMs != nil {
		return *x.TtlMs
	}
	return 0
}

type VectorPutRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VectorPutRes) Reset() {
	*x = VectorPutRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorPutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorPutRes) ProtoMessage() {}

func (x *VectorPutRes) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorPutRes.ProtoReflect.Descriptor instead.
func (*VectorPutRes) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{8}
}

func (x *VectorPutRes) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type VectorGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection string    `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector     []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"` // exact lookup by embedding
}

func (x *VectorGetReq) Reset() {
	*x = VectorGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorGetReq) ProtoMessage() {}

func (x *VectorGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorGetReq.ProtoReflect.Descriptor instead.
func (*VectorGetReq) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{9}
}

func (x *VectorGetReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorGetReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type VectorGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found   bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *VectorGetRes) Reset() {
	*x = VectorGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorGetRes) ProtoMessage() {}

func (x *VectorGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorGetRes.ProtoReflect.Descriptor instead.
func (*VectorGetRes) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{10}
}

func (x *VectorGetRes) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *VectorGetRes) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type VectorDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection string    `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector     []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *VectorDeleteReq) Reset() {
	*x = VectorDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDeleteReq) ProtoMessage() {}

func (x *VectorDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDeleteReq.ProtoReflect.Descriptor instead.
func (*VectorDeleteReq) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{11}
}

func (x *VectorDeleteReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorDeleteReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type VectorDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VectorDeleteRes) Reset() {
	*x = VectorDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDeleteRes) ProtoMessage() {}

func (x *VectorDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDeleteRes.ProtoReflect.Descriptor instead.
func (*VectorDeleteRes) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{12}
}

// VectorSearchReq is a cluster-wide k-nearest-neighbour query. The query vector is `query`; its
// length must equal the collection's dimensions.
type VectorSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection     string    `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Query          []float32 `protobuf:"fixed32,2,rep,packed,name=query,proto3" json:"query,omitempty"`
	K              uint32    `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	Nprobe         uint32    `protobuf:"varint,4,opt,name=nprobe,proto3" json:"nprobe,omitempty"`                                       // buckets to probe (Phase 2 routing); 0 = scatter to all holders
	EfSearch       uint32    `protobuf:"varint,5,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`                   // HNSW beam width
	Rerank         bool      `protobuf:"varint,6,opt,name=rerank,proto3" json:"rerank,omitempty"`                                       // exact-rescore ANN candidates
	IncludePayload bool      `protobuf:"varint,7,opt,name=include_payload,json=includePayload,proto3" json:"include_payload,omitempty"` // return payloads inline
}

func (x *VectorSearchReq) Reset() {
	*x = VectorSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchReq) ProtoMessage() {}

func (x *VectorSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchReq.ProtoReflect.Descriptor instead.
func (*VectorSearchReq) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{13}
}

func (x *VectorSearchReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VectorSearchReq) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *VectorSearchReq) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *VectorSearchReq) GetNprobe() uint32 {
	if x != nil {
		return x.Nprobe
	}
	return 0
}

func (x *VectorSearchReq) GetEfSearch() uint32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *VectorSearchReq) GetRerank() bool {
	if x != nil {
		return x.Rerank
	}
	return false
}

func (x *VectorSearchReq) GetIncludePayload() bool {
	if x != nil {
		return x.IncludePayload
	}
	return false
}

type Neighbor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vector   []float32 `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Payload  []byte    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Distance float64   `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"` // smaller = closer
	Score    float64   `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`       // larger = more similar
	VectorId string    `protobuf:"bytes,5,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{14}
}

func (x *Neighbor) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Neighbor) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Neighbor) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Neighbor) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Neighbor) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

type VectorSearchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neighbors    []*Neighbor   `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Meta         *ResponseMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Completeness Completeness  `protobuf:"varint,3,opt,name=completeness,proto3,enum=wavespan.v1.Completeness" json:"completeness,omitempty"`
}

func (x *VectorSearchRes) Reset() {
	*x = VectorSearchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchRes) ProtoMessage() {}

func (x *VectorSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchRes.ProtoReflect.Descriptor instead.
func (*VectorSearchRes) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{15}
}

func (x *VectorSearchRes) GetNeighbors() []*Neighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *VectorSearchRes) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *VectorSearchRes) GetCompleteness() Completeness {
	if x != nil {
		return x.Completeness
	}
	return Completeness_COMPLETENESS_UNSPECIFIED
}

// FloatVector wraps a vector for nested repeated-float fields (sampling, centroids).
type FloatVector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *FloatVector) Reset() {
	*x = FloatVector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatVector) ProtoMessage() {}

func (x *FloatVector) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatVector.ProtoReflect.Descriptor instead.
func (*FloatVector) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{16}
}

func (x *FloatVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// IvfCentroids is the trained, shared quantizer artifact for a collection (design/29 Phase 3.5):
// every node installs the same centroids so they agree on buckets. Versioned by qver — a retrain
// produces a higher qver and new buckets; old vectors stay put and re-advertise under the new qver.
type IvfCentroids struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection      string         `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Qver            uint32         `protobuf:"varint,2,opt,name=qver,proto3" json:"qver,omitempty"`
	Dim             uint32         `protobuf:"varint,3,opt,name=dim,proto3" json:"dim,omitempty"`
	L2              bool           `protobuf:"varint,4,opt,name=l2,proto3" json:"l2,omitempty"` // true = Euclidean; false = angular/dot
	Centroids       []*FloatVector `protobuf:"bytes,5,rep,name=centroids,proto3" json:"centroids,omitempty"`
	TrainedAtUnixMs int64          `protobuf:"varint,6,opt,name=trained_at_unix_ms,json=trainedAtUnixMs,proto3" json:"trained_at_unix_ms,omitempty"`
}

func (x *IvfCentroids) Reset() {
	*x = IvfCentroids{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IvfCentroids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IvfCentroids) ProtoMessage() {}

func (x *IvfCentroids) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IvfCentroids.ProtoReflect.Descriptor instead.
func (*IvfCentroids) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{17}
}

func (x *IvfCentroids) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *IvfCentroids) GetQver() uint32 {
	if x != nil {
		return x.Qver
	}
	return 0
}

func (x *IvfCentroids) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *IvfCentroids) GetL2() bool {
	if x != nil {
		return x.L2
	}
	return false
}

func (x *IvfCentroids) GetCentroids() []*FloatVector {
	if x != nil {
		return x.Centroids
	}
	return nil
}

func (x *IvfCentroids) GetTrainedAtUnixMs() int64 {
	if x != nil {
		return x.TrainedAtUnixMs
	}
	return 0
}

// SampleVectorsReq asks a node for a reservoir sample of its local vectors (for IVF training).
type SampleVectorsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Limit      uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *SampleVectorsReq) Reset() {
	*x = SampleVectorsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleVectorsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleVectorsReq) ProtoMessage() {}

func (x *SampleVectorsReq) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleVectorsReq.ProtoReflect.Descriptor instead.
func (*SampleVectorsReq) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{18}
}

func (x *SampleVectorsReq) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SampleVectorsReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SampleVectorsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vectors []*FloatVector `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
}

func (x *SampleVectorsRes) Reset() {
	*x = SampleVectorsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wavespan_v1_vector_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleVectorsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleVectorsRes) ProtoMessage() {}

func (x *SampleVectorsRes) ProtoReflect() protoreflect.Message {
	mi := &file_wavespan_v1_vector_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleVectorsRes.ProtoReflect.Descriptor instead.
func (*SampleVectorsRes) Descriptor() ([]byte, []int) {
	return file_wavespan_v1_vector_proto_rawDescGZIP(), []int{19}
}

func (x *SampleVectorsRes) GetVectors() []*FloatVector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

var File_wavespan_v1_vector_proto protoreflect.FileDescriptor

var file_wavespan_v1_vector_proto_rawDesc = []byte{
	0x0a, 0x18, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x18, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x79, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x03, 0x0a, 0x0c,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x69, 0x6d,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x43, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0d,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x2e, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x4f, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa5, 0x01, 0x0a, 0x0a, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x22, 0x0a,
	0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x22, 0x45, 0x0a, 0x10, 0x50, 0x75, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa2, 0x01,
	0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x66, 0x5f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x66, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x61, 0x63, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x72, 0x61, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x72, 0x61,
	0x6e, 0x6b, 0x22, 0x9e, 0x01, 0x0a, 0x09, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x69, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x41, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x68, 0x69,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73,
	0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x69, 0x74,
	0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x06, 0x74, 0x74, 0x6c,
	0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x74, 0x74, 0x6c,
	0x4d, 0x73, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x74, 0x6c, 0x5f, 0x6d, 0x73,
	0x22, 0x3e, 0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x2e, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x46, 0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02,
	0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x49, 0x0a, 0x0f, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x0f, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x66, 0x5f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x65, 0x66, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x08, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x64, 0x22, 0xb4, 0x01, 0x0a, 0x0f, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x52, 0x09, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x0c, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x0c, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0xc9, 0x01, 0x0a, 0x0c, 0x49, 0x76, 0x66, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x69, 0x64,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x71, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x71, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x64, 0x69, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x32, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6c, 0x32, 0x12, 0x36, 0x0a, 0x09, 0x63, 0x65, 0x6e, 0x74, 0x72,
	0x6f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x69, 0x64, 0x73, 0x12,
	0x2b, 0x0a, 0x12, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e,
	0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x22, 0x48, 0x0a, 0x10,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x46, 0x0a, 0x10, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x61,
	0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x32, 0x94,
	0x04, 0x0a, 0x0d, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x44, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x1f, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x09, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x50, 0x75, 0x74, 0x12, 0x19, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x09, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73,
	0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x4a,
	0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c,
	0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x77,
	0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x4a, 0x0a, 0x0c, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73,
	0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x4d, 0x0a, 0x0d, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x42, 0xa5, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61,
	0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6e, 0x6e, 0x69, 0x63, 0x6b, 0x2f, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x70, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x70, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x57, 0x58, 0x58, 0xaa, 0x02, 0x0b, 0x57, 0x61, 0x76, 0x65, 0x73,
	0x70, 0x61, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0b, 0x57, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61,
	0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x57, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0c, 0x57, 0x61, 0x76, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wavespan_v1_vector_proto_rawDescOnce sync.Once
	file_wavespan_v1_vector_proto_rawDescData = file_wavespan_v1_vector_proto_rawDesc
)

func file_wavespan_v1_vector_proto_rawDescGZIP() []byte {
	file_wavespan_v1_vector_proto_rawDescOnce.Do(func() {
		file_wavespan_v1_vector_proto_rawDescData = protoimpl.X.CompressGZIP(file_wavespan_v1_vector_proto_rawDescData)
	})
	return file_wavespan_v1_vector_proto_rawDescData
}

var file_wavespan_v1_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_wavespan_v1_vector_proto_goTypes = []interface{}{
	(*VectorRecord)(nil),        // 0: wavespan.v1.VectorRecord
	(*VectorMeta)(nil),          // 1: wavespan.v1.VectorMeta
	(*PutVectorRequest)(nil),    // 2: wavespan.v1.PutVectorRequest
	(*PutVectorResponse)(nil),   // 3: wavespan.v1.PutVectorResponse
	(*SearchLocalRequest)(nil),  // 4: wavespan.v1.SearchLocalRequest
	(*VectorHit)(nil),           // 5: wavespan.v1.VectorHit
	(*SearchLocalResponse)(nil), // 6: wavespan.v1.SearchLocalResponse
	(*VectorPutReq)(nil),        // 7: wavespan.v1.VectorPutReq
	(*VectorPutRes)(nil),        // 8: wavespan.v1.VectorPutRes
	(*VectorGetReq)(nil),        // 9: wavespan.v1.VectorGetReq
	(*VectorGetRes)(nil),        // 10: wavespan.v1.VectorGetRes
	(*VectorDeleteReq)(nil),     // 11: wavespan.v1.VectorDeleteReq
	(*VectorDeleteRes)(nil),     // 12: wavespan.v1.VectorDeleteRes
	(*VectorSearchReq)(nil),     // 13: wavespan.v1.VectorSearchReq
	(*Neighbor)(nil),            // 14: wavespan.v1.Neighbor
	(*VectorSearchRes)(nil),     // 15: wavespan.v1.VectorSearchRes
	(*FloatVector)(nil),         // 16: wavespan.v1.FloatVector
	(*IvfCentroids)(nil),        // 17: wavespan.v1.IvfCentroids
	(*SampleVectorsReq)(nil),    // 18: wavespan.v1.SampleVectorsReq
	(*SampleVectorsRes)(nil),    // 19: wavespan.v1.SampleVectorsRes
	nil,                         // 20: wavespan.v1.VectorRecord.MetadataEntry
	(*Version)(nil),             // 21: wavespan.v1.Version
	(*ResponseMeta)(nil),        // 22: wavespan.v1.ResponseMeta
	(Completeness)(0),           // 23: wavespan.v1.Completeness
	(*Value)(nil),               // 24: wavespan.v1.Value
}
var file_wavespan_v1_vector_proto_depIdxs = []int32{
	20, // 0: wavespan.v1.VectorRecord.metadata:type_name -> wavespan.v1.VectorRecord.MetadataEntry
	21, // 1: wavespan.v1.VectorRecord.version:type_name -> wavespan.v1.Version
	0,  // 2: wavespan.v1.PutVectorRequest.record:type_name -> wavespan.v1.VectorRecord
	5,  // 3: wavespan.v1.SearchLocalResponse.hits:type_name -> wavespan.v1.VectorHit
	21, // 4: wavespan.v1.VectorPutRes.version:type_name -> wavespan.v1.Version
	14, // 5: wavespan.v1.VectorSearchRes.neighbors:type_name -> wavespan.v1.Neighbor
	22, // 6: wavespan.v1.VectorSearchRes.meta:type_name -> wavespan.v1.ResponseMeta
	23, // 7: wavespan.v1.VectorSearchRes.completeness:type_name -> wavespan.v1.Completeness
	16, // 8: wavespan.v1.IvfCentroids.centroids:type_name -> wavespan.v1.FloatVector
	16, // 9: wavespan.v1.SampleVectorsRes.vectors:type_name -> wavespan.v1.FloatVector
	24, // 10: wavespan.v1.VectorRecord.MetadataEntry.value:type_name -> wavespan.v1.Value
	2,  // 11: wavespan.v1.VectorService.Put:input_type -> wavespan.v1.PutVectorRequest
	4,  // 12: wavespan.v1.VectorService.SearchLocal:input_type -> wavespan.v1.SearchLocalRequest
	7,  // 13: wavespan.v1.VectorService.VectorPut:input_type -> wavespan.v1.VectorPutReq
	9,  // 14: wavespan.v1.VectorService.VectorGet:input_type -> wavespan.v1.VectorGetReq
	11, // 15: wavespan.v1.VectorService.VectorDelete:input_type -> wavespan.v1.VectorDeleteReq
	13, // 16: wavespan.v1.VectorService.VectorSearch:input_type -> wavespan.v1.VectorSearchReq
	18, // 17: wavespan.v1.VectorService.SampleVectors:input_type -> wavespan.v1.SampleVectorsReq
	3,  // 18: wavespan.v1.VectorService.Put:output_type -> wavespan.v1.PutVectorResponse
	6,  // 19: wavespan.v1.VectorService.SearchLocal:output_type -> wavespan.v1.SearchLocalResponse
	8,  // 20: wavespan.v1.VectorService.VectorPut:output_type -> wavespan.v1.VectorPutRes
	10, // 21: wavespan.v1.VectorService.VectorGet:output_type -> wavespan.v1.VectorGetRes
	12, // 22: wavespan.v1.VectorService.VectorDelete:output_type -> wavespan.v1.VectorDeleteRes
	15, // 23: wavespan.v1.VectorService.VectorSearch:output_type -> wavespan.v1.VectorSearchRes
	19, // 24: wavespan.v1.VectorService.SampleVectors:output_type -> wavespan.v1.SampleVectorsRes
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wavespan_v1_vector_proto_init() }
func file_wavespan_v1_vector_proto_init() {
	if File_wavespan_v1_vector_proto != nil {
		return
	}
	file_wavespan_v1_common_proto_init()
	file_wavespan_v1_cypher_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_wavespan_v1_vector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutVectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutVectorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchLocalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorHit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchLocalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorPutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorPutRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Neighbor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorSearchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatVector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IvfCentroids); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleVectorsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wavespan_v1_vector_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleVectorsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_wavespan_v1_vector_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wavespan_v1_vector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wavespan_v1_vector_proto_goTypes,
		DependencyIndexes: file_wavespan_v1_vector_proto_depIdxs,
		MessageInfos:      file_wavespan_v1_vector_proto_msgTypes,
	}.Build()
	File_wavespan_v1_vector_proto = out.File
	file_wavespan_v1_vector_proto_rawDesc = nil
	file_wavespan_v1_vector_proto_goTypes = nil
	file_wavespan_v1_vector_proto_depIdxs = nil
}
